INSERT INTO cfg_parameter (parameter, tablename, value) VALUES ('max_nnml_train_records', '', '10');
INSERT INTO cfg_parameter (parameter, tablename, value) VALUES ('max_nnml_model_records', '', '10');
INSERT INTO cfg_parameter (parameter, tablename, value) VALUES ('nnml_devicetypeid_threshold', '', '0.95');
INSERT INTO cfg_parameter (parameter, tablename, value) VALUES ('nnml_manufacturerid_threshold', '', '0.95');
INSERT INTO cfg_parameter (parameter, tablename, value) VALUES ('max_hist_dump_records', '', '10');
INSERT INTO cfg_parameter (parameter, tablename, value) VALUES ('main_host_keep_inactive', '', '90');
INSERT INTO cfg_parameter (parameter, tablename, value) VALUES ('zbx_host_keep_inactive', '', '30');
INSERT INTO cfg_parameter (parameter, tablename, value) VALUES ('main_host_change_delay', '', '3');
INSERT INTO cfg_parameter (parameter, tablename, value) VALUES ('zbx_history_records', '', '10');
INSERT INTO cfg_parameter (parameter, tablename, value) VALUES ('zbx_host_keep_monitored', '', '14');
INSERT INTO cfg_parameter (parameter, tablename, value) VALUES ('zbx_host_keep_enabled', '', '21');
INSERT INTO cfg_parameter (parameter, tablename, value) VALUES ('zbx_device_host_template', '', 'Template Omnisiah Device');
INSERT INTO cfg_parameter (parameter, tablename, value) VALUES ('zbx_group_host_template', '', 'Template Omnisiah Group Host');
