CREATE TABLE IF NOT EXISTS code_layer ( 
  layerid INT UNSIGNED NOT NULL PRIMARY KEY, 
  layer VARCHAR(256) NOT NULL UNIQUE) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS code_program ( 
  programid INT UNSIGNED NOT NULL PRIMARY KEY, 
  program VARCHAR(256) NOT NULL UNIQUE, 
  enabled BOOLEAN NOT NULL DEFAULT TRUE, 
  layerid INT UNSIGNED NOT NULL, 
  CONSTRAINT layerid_cp FOREIGN KEY (layerid) REFERENCES code_layer (layerid) ON DELETE CASCADE ON UPDATE CASCADE) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS code_program_launch ( 
  priority INT UNSIGNED NOT NULL PRIMARY KEY, 
  programid INT UNSIGNED NOT NULL, 
  parameters VARCHAR(1024) DEFAULT NULL, 
  wait BOOLEAN NOT NULL DEFAULT TRUE, 
  enabled BOOLEAN NOT NULL DEFAULT TRUE, 
  CONSTRAINT programid_cpl FOREIGN KEY (programid) REFERENCES code_program (programid) ON DELETE CASCADE ON UPDATE CASCADE) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS code_program_query ( 
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY, 
  programid INT UNSIGNED NOT NULL, 
  stage INT UNSIGNED NOT NULL, 
  priority INT UNSIGNED NOT NULL, 
  parameter VARCHAR(256) DEFAULT NULL, 
  tablename VARCHAR(256) DEFAULT NULL,
  query VARCHAR(8192) NOT NULL DEFAULT '', 
  enabled BOOLEAN NOT NULL DEFAULT TRUE, 
  nrepeat SMALLINT UNSIGNED NOT NULL DEFAULT 1, 
  UNIQUE KEY psp (programid, stage, priority), 
  KEY stage (stage), 
  KEY priority (priority),   
  CONSTRAINT programid_cpq FOREIGN KEY (programid) REFERENCES code_program (programid) ON DELETE CASCADE ON UPDATE CASCADE) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS code_action ( 
  actionid INT UNSIGNED NOT NULL PRIMARY KEY, 
  action VARCHAR(256) NOT NULL UNIQUE) ENGINE=InnoDB;
