CREATE TABLE IF NOT EXISTS log_program ( 
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY, 
  programid INT UNSIGNED NOT NULL, 
  queryid INT UNSIGNED DEFAULT NULL, 
  actionid INT UNSIGNED NOT NULL, 
  actiondt DATETIME NOT NULL DEFAULT NOW(), 
  KEY actiondt (actiondt), 
  CONSTRAINT programid_lp FOREIGN KEY (programid) REFERENCES code_program (programid) ON DELETE CASCADE ON UPDATE CASCADE, 
  CONSTRAINT queryid_lp FOREIGN KEY (queryid) REFERENCES code_program_query (id) ON DELETE CASCADE ON UPDATE CASCADE, 
  CONSTRAINT actionid_lp FOREIGN KEY (actionid) REFERENCES code_action (actionid) ON DELETE CASCADE ON UPDATE CASCADE) ENGINE=InnoDB;
