CREATE TABLE IF NOT EXISTS main_host ( 
  hostid BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT, 
  hostuuid VARCHAR(256) NOT NULL, 
  idtype INT UNSIGNED NOT NULL, 
  ip VARCHAR(39) DEFAULT NULL, 
  mac VARCHAR(12) DEFAULT NULL, 
  name varchar(256) DEFAULT NULL,
  hostname varchar(100) DEFAULT NULL,
  manufacturerid INT UNSIGNED DEFAULT NULL,
  devicetypeid INT UNSIGNED NOT NULL, 
  controllerid BIGINT DEFAULT NULL, 
  idoncontroller VARCHAR(256) DEFAULT NULL, 
  ipprefixid INT UNSIGNED DEFAULT NULL, 
  vlan INT UNSIGNED NOT NULL DEFAULT 0, 
  roleid INT UNSIGNED DEFAULT NULL, 
  ispublic BOOLEAN DEFAULT NULL, 
  macvendorid VARCHAR(12) DEFAULT NULL, 
  active BOOLEAN DEFAULT TRUE, 
  created DATETIME DEFAULT NOW(), 
  last_active DATETIME DEFAULT NOW(), 
  snmp_community VARCHAR(50) DEFAULT NULL,
  change_delay SMALLINT NOT NULL, 
  siteid INT UNSIGNED NOT NULL DEFAULT 0,
  UNIQUE KEY hosttype (hostuuid, idtype), 
  KEY hostuuid (hostuuid), 
  KEY idtype (idtype), 
  KEY ip (ip), 
  KEY mac (mac), 
  KEY name (name), 
  KEY manufacturerid (manufacturerid), 
  KEY devicetypeid (devicetypeid), 
  KEY controllerid (controllerid), 
  KEY ipprefixid (ipprefixid), 
  KEY roleid (roleid), 
  KEY macvendorid (macvendorid), 
  KEY active (active), 
  KEY last_active (last_active), 
  KEY change_delay (change_delay), 
  KEY siteid (siteid), 
  CONSTRAINT roleid_mh FOREIGN KEY (roleid) REFERENCES ref_subnet_role (subnet_roleid) ON DELETE SET NULL ON UPDATE CASCADE, 
  CONSTRAINT macvendorid_mh FOREIGN KEY (macvendorid) REFERENCES info_mac (assignment) ON DELETE SET NULL ON UPDATE CASCADE, 
  CONSTRAINT manufacturerid_mh FOREIGN KEY (manufacturerid) REFERENCES ref_manufacturer (manufacturerid) ON DELETE SET NULL ON UPDATE CASCADE, 
  CONSTRAINT devicetypeid_mh FOREIGN KEY (devicetypeid) REFERENCES ref_devicetype (devicetypeid) ON DELETE CASCADE ON UPDATE CASCADE, 
  CONSTRAINT ipprefixid_mh FOREIGN KEY (ipprefixid) REFERENCES ref_ipprefix (ipprefixid) ON DELETE SET NULL ON UPDATE CASCADE, 
  CONSTRAINT controllerid_mh FOREIGN KEY (controllerid) REFERENCES main_host (hostid) ON DELETE SET NULL ON UPDATE CASCADE, 
  CONSTRAINT idtype_mh FOREIGN KEY (idtype) REFERENCES ref_host_idtype (id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT siteid_mh FOREIGN KEY (siteid) REFERENCES ref_site (siteid) ON DELETE SET DEFAULT ON UPDATE CASCADE  
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS main_host_uuid ( 
  id BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT, 
  hostid BIGINT NOT NULL, 
  uuid_type INT UNSIGNED NOT NULL, 
  uuid VARCHAR(256) NOT NULL, 
  UNIQUE KEY uuidtype (uuid_type, uuid), 
  KEY uuid_type (uuid_type), 
  KEY hostid (hostid), 
  KEY uuid (uuid), 
  CONSTRAINT hostid_mhu FOREIGN KEY (hostid) REFERENCES main_host (hostid) ON DELETE CASCADE ON UPDATE CASCADE, 
  CONSTRAINT uuid_type_mhu FOREIGN KEY (uuid_type) REFERENCES ref_host_uuid (id) ON DELETE CASCADE ON UPDATE CASCADE 
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS main_host_link ( 
  id BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT, 
  hostid BIGINT NOT NULL, 
  linkid INT UNSIGNED NOT NULL, 
  uuid VARCHAR(256) NOT NULL, 
  UNIQUE KEY hostlink (hostid, linkid), 
  KEY linkid (linkid), 
  KEY hostid (hostid), 
  KEY uuid (uuid), 
  CONSTRAINT hostid_mhl FOREIGN KEY (hostid) REFERENCES main_host (hostid) ON DELETE CASCADE ON UPDATE CASCADE, 
  CONSTRAINT linkid_mhl FOREIGN KEY (linkid) REFERENCES ref_host_link (linkid) ON DELETE CASCADE ON UPDATE CASCADE 
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS main_if (
  ifid BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT, 
  device VARCHAR(39) NOT NULL, 
  ifindex INT UNSIGNED NOT NULL, 
  ifdescr VARCHAR(256) DEFAULT NULL,
  ifname VARCHAR(100) DEFAULT NULL,
  ifalias VARCHAR(256) DEFAULT NULL,
  ifadminstatus SMALLINT UNSIGNED NOT NULL DEFAULT 2, 
  ifoperstatus SMALLINT UNSIGNED NOT NULL DEFAULT 4, 
  ip VARCHAR(39) DEFAULT NULL, 
  netmask VARCHAR(39) DEFAULT NULL, 
  netnum INT UNSIGNED DEFAULT NULL, 
  siteid INT UNSIGNED NOT NULL DEFAULT 0, 
  vlanid INT UNSIGNED DEFAULT NULL, 
  vlan INT UNSIGNED NOT NULL DEFAULT 0, 
  roleid INT UNSIGNED DEFAULT NULL, 
  connectedto BIGINT DEFAULT NULL,
  macs INT UNSIGNED NOT NULL DEFAULT 0,
  ifphysaddress VARCHAR(12) DEFAULT NULL, 
  ifphysaddressnum BIGINT UNSIGNED DEFAULT NULL, 
  macvendorid VARCHAR(12) DEFAULT NULL, 
  active BOOLEAN DEFAULT TRUE, 
  created DATETIME DEFAULT NOW(), 
  last_active DATETIME DEFAULT NOW(), 
  UNIQUE KEY deviceifindex (device, ifindex), 
  KEY device (device),
  KEY ifindex (ifindex),
  KEY ifdescr (ifdescr), 
  KEY ifname (ifname), 
  KEY ifalias (ifalias), 
  KEY ifadminstatus (ifadminstatus), 
  KEY ifoperstatus (ifoperstatus), 
  KEY ip (ip), 
  KEY netnum (netnum), 
  KEY siteid (siteid), 
  KEY vlanid (vlanid), 
  KEY vlan (vlan), 
  KEY roleid (roleid), 
  KEY macs (macs), 
  KEY connectedto (connectedto), 
  KEY ifphysaddress (ifphysaddress), 
  KEY ifphysaddressnum (ifphysaddressnum), 
  KEY macvendorid (macvendorid), 
  KEY active (active), 
  KEY last_active (last_active), 
  CONSTRAINT vlanid_mif FOREIGN KEY (vlanid) REFERENCES ref_vlan (vlanid) ON DELETE SET NULL ON UPDATE CASCADE, 
  CONSTRAINT roleid_mif FOREIGN KEY (roleid) REFERENCES ref_subnet_role (subnet_roleid) ON DELETE SET NULL ON UPDATE CASCADE, 
  CONSTRAINT siteid_mif FOREIGN KEY (siteid) REFERENCES ref_site (siteid) ON DELETE SET DEFAULT ON UPDATE CASCADE, 
  CONSTRAINT connectedto_mif FOREIGN KEY (connectedto) REFERENCES main_if (ifid) ON DELETE SET NULL ON UPDATE CASCADE, 
  CONSTRAINT macvendorid_mif FOREIGN KEY (macvendorid) REFERENCES info_mac (assignment) ON DELETE SET NULL ON UPDATE CASCADE 
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS main_arp_device (
  arpid BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT, 
  device VARCHAR(39) NOT NULL, 
  ip VARCHAR(39) NOT NULL, 
  ipnum BIGINT UNSIGNED NOT NULL, 
  mac VARCHAR(12) NOT NULL, 
  vlanid INT UNSIGNED DEFAULT NULL, 
  vlan INT UNSIGNED NOT NULL DEFAULT 0, 
  roleid INT UNSIGNED DEFAULT NULL, 
  siteid INT UNSIGNED NOT NULL DEFAULT 0, 
  ipprefixid INT UNSIGNED DEFAULT NULL, 
  ifindex INT UNSIGNED DEFAULT NULL, 
  ispublic BOOLEAN DEFAULT TRUE, 
  active BOOLEAN DEFAULT TRUE, 
  created DATETIME DEFAULT NOW(), 
  last_active DATETIME DEFAULT NOW(), 
  UNIQUE KEY deviceip (device, ip), 
  KEY device (device), 
  KEY ip (ip), 
  KEY ipnum (ipnum), 
  KEY mac (mac), 
  KEY vlanid (vlanid), 
  KEY vlan (vlan), 
  KEY roleid (roleid), 
  KEY siteid (siteid), 
  KEY ipprefixid (ipprefixid), 
  KEY ifindex (ifindex), 
  KEY ispublic (ispublic), 
  KEY active (active), 
  KEY last_active (last_active), 
  CONSTRAINT vlanid_mar FOREIGN KEY (vlanid) REFERENCES ref_vlan (vlanid) ON DELETE SET NULL ON UPDATE CASCADE, 
  CONSTRAINT roleid_mar FOREIGN KEY (roleid) REFERENCES ref_subnet_role (subnet_roleid) ON DELETE SET NULL ON UPDATE CASCADE, 
  CONSTRAINT ipprefixid_mar FOREIGN KEY (ipprefixid) REFERENCES ref_ipprefix (ipprefixid) ON DELETE SET NULL ON UPDATE CASCADE, 
  CONSTRAINT siteid_mar FOREIGN KEY (siteid) REFERENCES ref_site (siteid) ON DELETE SET DEFAULT ON UPDATE CASCADE 
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS main_arp_site (
  arpid BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT, 
  siteid INT UNSIGNED NOT NULL DEFAULT 0, 
  ip VARCHAR(39) NOT NULL, 
  ipnum BIGINT UNSIGNED NOT NULL, 
  mac VARCHAR(12) NOT NULL, 
  vlanid INT UNSIGNED DEFAULT NULL, 
  vlan INT UNSIGNED NOT NULL DEFAULT 0, 
  roleid INT UNSIGNED DEFAULT NULL, 
  ipprefixid INT UNSIGNED DEFAULT NULL, 
  ispublic BOOLEAN DEFAULT TRUE, 
  active BOOLEAN DEFAULT TRUE, 
  created DATETIME DEFAULT NOW(), 
  last_active DATETIME DEFAULT NOW(), 
  UNIQUE KEY ipsite (ip, siteid), 
  KEY ip (ip), 
  KEY ipnum (ipnum), 
  KEY mac (mac), 
  KEY vlanid (vlanid), 
  KEY vlan (vlan), 
  KEY roleid (roleid), 
  KEY ipprefixid (ipprefixid), 
  KEY siteid (siteid), 
  KEY ispublic (ispublic), 
  KEY active (active), 
  KEY last_active (last_active), 
  CONSTRAINT vlanid_mas FOREIGN KEY (vlanid) REFERENCES ref_vlan (vlanid) ON DELETE SET NULL ON UPDATE CASCADE, 
  CONSTRAINT roleid_mas FOREIGN KEY (roleid) REFERENCES ref_subnet_role (subnet_roleid) ON DELETE SET NULL ON UPDATE CASCADE, 
  CONSTRAINT ipprefixid_mas FOREIGN KEY (ipprefixid) REFERENCES ref_ipprefix (ipprefixid) ON DELETE SET NULL ON UPDATE CASCADE, 
  CONSTRAINT siteid_mas FOREIGN KEY (siteid) REFERENCES ref_site (siteid) ON DELETE SET DEFAULT ON UPDATE CASCADE 
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS main_arp (
  arpid BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT, 
  ip VARCHAR(39) NOT NULL UNIQUE, 
  ipnum BIGINT UNSIGNED NOT NULL, 
  mac VARCHAR(12) NOT NULL, 
  vlanid INT UNSIGNED DEFAULT NULL, 
  vlan INT UNSIGNED NOT NULL DEFAULT 0, 
  roleid INT UNSIGNED DEFAULT NULL, 
  ipprefixid INT UNSIGNED DEFAULT NULL, 
  siteid INT UNSIGNED NOT NULL DEFAULT 0, 
  ispublic BOOLEAN DEFAULT TRUE, 
  active BOOLEAN DEFAULT TRUE, 
  created DATETIME DEFAULT NOW(), 
  last_active DATETIME DEFAULT NOW(), 
  KEY ipnum (ipnum), 
  KEY mac (mac), 
  KEY vlanid (vlanid), 
  KEY vlan (vlan), 
  KEY ipprefixid (ipprefixid), 
  KEY siteid (siteid), 
  KEY roleid (roleid), 
  KEY ispublic (ispublic), 
  KEY active (active), 
  KEY last_active (last_active), 
  CONSTRAINT vlanid_ma FOREIGN KEY (vlanid) REFERENCES ref_vlan (vlanid) ON DELETE SET NULL ON UPDATE CASCADE, 
  CONSTRAINT roleid_ma FOREIGN KEY (roleid) REFERENCES ref_subnet_role (subnet_roleid) ON DELETE SET NULL ON UPDATE CASCADE, 
  CONSTRAINT ipprefixid_ma FOREIGN KEY (ipprefixid) REFERENCES ref_ipprefix (ipprefixid) ON DELETE SET NULL ON UPDATE CASCADE, 
  CONSTRAINT siteid_ma FOREIGN KEY (siteid) REFERENCES ref_site (siteid) ON DELETE SET DEFAULT ON UPDATE CASCADE 
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS main_mac_device (
  macid BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  device VARCHAR(39) NOT NULL, 
  mac VARCHAR(12) NOT NULL,
  macnum BIGINT UNSIGNED NOT NULL, 
  port INT UNSIGNED NOT NULL, 
  vlan INT UNSIGNED NOT NULL DEFAULT 0, 
  siteid INT UNSIGNED NOT NULL DEFAULT 0, 
  vlanid INT UNSIGNED DEFAULT NULL, 
  roleid INT UNSIGNED DEFAULT NULL, 
  vendorid VARCHAR(12) DEFAULT NULL, 
  active BOOLEAN DEFAULT TRUE, 
  created DATETIME DEFAULT NOW(), 
  last_active DATETIME DEFAULT NOW(), 
  UNIQUE KEY devicemacvlan (device, mac, vlan), 
  KEY devicemac (device, mac),
  KEY mac (mac), 
  KEY macnum (macnum), 
  KEY device (device),
  KEY port (port),
  KEY vlan (vlan),
  KEY siteid (siteid), 
  KEY vlanid (vlanid), 
  KEY roleid (roleid), 
  KEY vendorid (vendorid), 
  KEY active (active), 
  KEY last_active (last_active), 
  CONSTRAINT vlanid_mmd FOREIGN KEY (vlanid) REFERENCES ref_vlan (vlanid) ON DELETE SET NULL ON UPDATE CASCADE, 
  CONSTRAINT roleid_mmd FOREIGN KEY (roleid) REFERENCES ref_subnet_role (subnet_roleid) ON DELETE SET NULL ON UPDATE CASCADE, 
  CONSTRAINT siteid_mmd FOREIGN KEY (siteid) REFERENCES ref_site (siteid) ON DELETE SET DEFAULT ON UPDATE CASCADE, 
  CONSTRAINT macid_mmd FOREIGN KEY (vendorid) REFERENCES info_mac (assignment) ON DELETE SET NULL ON UPDATE CASCADE 
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS main_mac_site (
  macid BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  device VARCHAR(39) NOT NULL, 
  mac VARCHAR(12) NOT NULL,
  macnum BIGINT UNSIGNED NOT NULL, 
  port INT UNSIGNED NOT NULL, 
  vlan INT UNSIGNED NOT NULL DEFAULT 0, 
  siteid INT UNSIGNED NOT NULL DEFAULT 0, 
  vlanid INT UNSIGNED DEFAULT NULL, 
  roleid INT UNSIGNED DEFAULT NULL, 
  vendorid VARCHAR(12) DEFAULT NULL, 
  active BOOLEAN DEFAULT TRUE, 
  created DATETIME DEFAULT NOW(), 
  last_active DATETIME DEFAULT NOW(), 
  UNIQUE KEY sitemacvlan (siteid, mac, vlan), 
  KEY sitemac (siteid, mac),
  KEY mac (mac), 
  KEY macnum (macnum), 
  KEY device (device),
  KEY port (port),
  KEY vlan (vlan),
  KEY siteid (siteid), 
  KEY vlanid (vlanid), 
  KEY roleid (roleid), 
  KEY vendorid (vendorid), 
  KEY active (active), 
  KEY last_active (last_active), 
  CONSTRAINT vlanid_mms FOREIGN KEY (vlanid) REFERENCES ref_vlan (vlanid) ON DELETE SET NULL ON UPDATE CASCADE, 
  CONSTRAINT roleid_mms FOREIGN KEY (roleid) REFERENCES ref_subnet_role (subnet_roleid) ON DELETE SET NULL ON UPDATE CASCADE, 
  CONSTRAINT siteid_mms FOREIGN KEY (siteid) REFERENCES ref_site (siteid) ON DELETE SET DEFAULT ON UPDATE CASCADE, 
  CONSTRAINT macid_mms FOREIGN KEY (vendorid) REFERENCES info_mac (assignment) ON DELETE SET NULL ON UPDATE CASCADE 
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS main_mac (
  macid BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  device VARCHAR(39) NOT NULL, 
  mac VARCHAR(12) NOT NULL,
  macnum BIGINT UNSIGNED NOT NULL, 
  port INT UNSIGNED NOT NULL, 
  siteid INT UNSIGNED NOT NULL DEFAULT 0, 
  vlan INT UNSIGNED NOT NULL DEFAULT 0, 
  roleid INT UNSIGNED DEFAULT NULL, 
  vendorid VARCHAR(12) DEFAULT NULL, 
  active BOOLEAN DEFAULT TRUE, 
  created DATETIME DEFAULT NOW(), 
  last_active DATETIME DEFAULT NOW(), 
  UNIQUE KEY macvlan (mac, vlan), 
  KEY mac (mac), 
  KEY macnum (macnum), 
  KEY device (device),
  KEY port (port),
  KEY vlan (vlan),
  KEY siteid (siteid), 
  KEY roleid (roleid), 
  KEY vendorid (vendorid), 
  KEY active (active), 
  KEY last_active (last_active), 
  CONSTRAINT roleid_mm FOREIGN KEY (roleid) REFERENCES ref_subnet_role (subnet_roleid) ON DELETE SET NULL ON UPDATE CASCADE, 
  CONSTRAINT macid_mm FOREIGN KEY (vendorid) REFERENCES info_mac (assignment) ON DELETE SET NULL ON UPDATE CASCADE, 
  CONSTRAINT siteid_mm FOREIGN KEY (siteid) REFERENCES ref_site (siteid) ON DELETE SET DEFAULT ON UPDATE CASCADE 
) ENGINE=InnoDB;
