INSERT INTO ref_vrf (netboxid, vrf, description, enforce_unique) VALUES (NULL, '', NULL, NULL);
UPDATE ref_vrf SET vrfid=0 WHERE vrfid=(SELECT MAX(vrfid) FROM ref_vrf);

INSERT INTO ref_region (regionid, netboxid, region, region_alias, description, parentid) VALUES (0, NULL, '', '', NULL, NULL);

INSERT INTO ref_site (siteid, netboxid, site, site_alias, description, active, regionid, groupid, tenantid, facility, time_zone, physical_address, shipping_address, latitude, longitude, contact_name, contact_phone, contact_email, importance, comments) VALUES (0, NULL, '', '', NULL, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL);

INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (0, NULL, '', '', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (1000, NULL, 'Undefined', 'undefined', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (1, NULL, 'Activaire', 'activaire', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (2, NULL, 'Advidia', 'advidia', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (3, NULL, 'APC', 'apc', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (4, NULL, 'Apple', 'apple', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (5, NULL, 'Arcules', 'arcules', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (6, NULL, 'Arista', 'arista', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (7, NULL, 'Ashly', 'ashly', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (8, NULL, 'Audinate', 'audinate', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (9, NULL, 'Avaya', 'avaya', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (10, NULL, 'Axis', 'axis', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (11, NULL, 'Biamp', 'biamp', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (12, NULL, 'Bosch', 'bosch', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (13, NULL, 'Brocade', 'brocade', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (14, NULL, 'Brother', 'brother', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (15, NULL, 'BSS', 'bss', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (16, NULL, 'Canon', 'canon', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (17, NULL, 'Cisco', 'cisco', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (18, NULL, 'Crestron', 'crestron', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (19, NULL, 'Dell', 'dell', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (20, NULL, 'Digium', 'digium', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (21, NULL, 'DMX', 'dmx', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (22, NULL, 'Eaton', 'eaton', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (23, NULL, 'Enplug', 'enplug', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (24, NULL, 'Epson', 'epson', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (25, NULL, 'Fortinet', 'fortinet', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (26, NULL, 'Furman', 'furman', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (27, NULL, 'Geist', 'geist', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (28, NULL, 'Gigaset', 'gigaset', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (29, NULL, 'Grandstream', 'grandstream', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (30, NULL, 'Hikvision', 'hikvision', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (31, NULL, 'Hitachi', 'hitachi', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (32, NULL, 'Honeywell', 'honeywell', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (33, NULL, 'HP', 'hp', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (34, NULL, 'Intel', 'intel', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (35, NULL, 'Juniper', 'juniper', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (36, NULL, 'Konfitel', 'konfitel', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (37, NULL, 'Legrand', 'legrand', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (38, NULL, 'Lenovo', 'lenovo', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (39, NULL, 'LG', 'lg', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (40, NULL, 'LifeSafety', 'lifesafety', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (41, NULL, 'Mercury Security', 'mercury-security', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (42, NULL, 'Mersive', 'mersive', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (43, NULL, 'Microsoft', 'microsoft', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (44, NULL, 'Mikrotik', 'mikrotik', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (45, NULL, 'Minix', 'minix', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (46, NULL, 'Mitsubishi', 'mitsubishi', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (47, NULL, 'NEC', 'nec', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (48, NULL, 'Netgear', 'netgear', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (49, NULL, 'Opengear', 'opengear', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (50, NULL, 'Palo Alto', 'palo-alto', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (51, NULL, 'Panasonic', 'panasonic', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (52, NULL, 'Panduit', 'panduit', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (53, NULL, 'Polycom', 'polycom', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (54, NULL, 'QNAP', 'qnap', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (55, NULL, 'QSC', 'qsc', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (56, NULL, 'Raspberry Pi', 'raspberry-pi', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (57, NULL, 'Riello', 'riello', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (58, NULL, 'Ruckus', 'ruckus', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (59, NULL, 'S2 Security', 's2-security', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (60, NULL, 'Sennheiser', 'sennheiser', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (61, NULL, 'Shure', 'shure', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (62, NULL, 'Siemens', 'siemens', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (63, NULL, 'Snom', 'snom', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (64, NULL, 'Sonos', 'sonos', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (65, NULL, 'Sony', 'sony', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (66, NULL, 'Super Micro', 'super-micro', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (67, NULL, 'Tesira', 'tesira', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (68, NULL, 'Ubiquiti', 'ubiquiti', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (69, NULL, 'VMWare', 'vmware', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (70, NULL, 'Wibrain', 'wibrain', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (71, NULL, 'Xerox', 'xerox', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (72, NULL, 'Yealink', 'yealink', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (73, NULL, '2n telekomunikace', '2n-telekomunikace', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (74, NULL, '3par data', '3par-data', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (75, NULL, 'Absolute acoustics', 'absolute-acoustics', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (76, NULL, 'Aiphone', 'aiphone', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (77, NULL, 'Alcatel Lucent', 'alcatel-lucent', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (78, NULL, 'Amazon', 'amazon', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (79, NULL, 'Ampak', 'ampak', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (80, NULL, 'Asix', 'asix', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (81, NULL, 'Asustek', 'asustek', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (82, NULL, 'Belkin', 'belkin', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (83, NULL, 'Bose', 'bose', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (84, NULL, 'Broadcom', 'broadcom', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (85, NULL, 'D-Link', 'd-link', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (86, NULL, 'Draytek', 'draytek', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (87, NULL, 'EMC', 'emc', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (88, NULL, 'Espressif', 'espressif', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (89, NULL, 'Extron', 'extron', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (90, NULL, 'Fujifilm', 'fujifilm', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (91, NULL, 'Fujitsu', 'fujitsu', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (92, NULL, 'GigaByte', 'gigabyte', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (93, NULL, 'Google', 'google', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (94, NULL, 'Huawei', 'huawei', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (95, NULL, 'IBM', 'ibm', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (96, NULL, 'Inforce', 'inforce', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (97, NULL, 'Innosys', 'innosys', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (98, NULL, 'Inpro', 'inpro', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (99, NULL, 'Konica Minolta', 'konica-minolta', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (100, NULL, 'Kyocera', 'kyocera', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (101, NULL, 'Lantronix', 'lantronix', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (102, NULL, 'Lexmark', 'lexmark', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (103, NULL, 'Lifesize', 'lifesize', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (104, NULL, 'Linksys', 'linksys', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (105, NULL, 'LiteOn', 'liteon', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (106, NULL, 'Logitech', 'logitech', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (107, NULL, 'Microchip', 'microchip', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (108, NULL, 'Motorola', 'motorola', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (109, NULL, 'Moxa', 'moxa', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (110, NULL, 'Multitech', 'multitech', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (111, NULL, 'Neatframe', 'neatframe', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (112, NULL, 'Nintendo', 'nintendo', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (113, NULL, 'Nokia', 'nokia', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (114, NULL, 'NVidia', 'nvidia', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (115, NULL, 'Obihai', 'obihai', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (116, NULL, 'Parallels', 'parallels', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (117, NULL, 'PCS systemtechnik', 'pcs-systemtechnik', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (118, NULL, 'QLogic', 'qlogic', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (119, NULL, 'Quanta', 'quanta', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (120, NULL, 'Realtek', 'realtek', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (121, NULL, 'Ricoh', 'ricoh', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (122, NULL, 'RTX Telecom', 'rtx-telecom', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (123, NULL, 'Samsung', 'samsung', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (124, NULL, 'Sharp', 'sharp', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (125, NULL, 'Sonicwall', 'sonicwall', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (126, NULL, 'Sophos', 'sophos', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (127, NULL, 'Texas Instruments', 'ti', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (128, NULL, 'TP-Link', 'tp-link', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (129, NULL, 'Vantage', 'vantage', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (130, NULL, 'VCS', 'vcs', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (131, NULL, 'Viavideo', 'viavideo', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (132, NULL, 'Western Digital', 'wd', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (133, NULL, 'Wistron', 'wistron', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (134, NULL, 'Xiaomi', 'xiaomi', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (135, NULL, 'ZTE', 'zte', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (136, NULL, 'Zyxel', 'zyxel', NULL);

INSERT INTO ref_devicerole (deviceroleid, netboxid, devicerole, devicerole_alias, description, vm_role) VALUES (0, NULL, '', '', NULL, NULL);
INSERT INTO ref_devicerole (deviceroleid, netboxid, devicerole, devicerole_alias, description, vm_role) VALUES (1000, NULL, 'Undefined', 'undefined', NULL, NULL);
INSERT INTO ref_devicerole (deviceroleid, netboxid, devicerole, devicerole_alias, description, vm_role) VALUES (1, NULL, 'Access Blade', 'access-blade', NULL, NULL);
INSERT INTO ref_devicerole (deviceroleid, netboxid, devicerole, devicerole_alias, description, vm_role) VALUES (2, NULL, 'Access Chassis', 'access-chassis', NULL, NULL);
INSERT INTO ref_devicerole (deviceroleid, netboxid, devicerole, devicerole_alias, description, vm_role) VALUES (3, NULL, 'Access Control', 'access-control', NULL, NULL);
INSERT INTO ref_devicerole (deviceroleid, netboxid, devicerole, devicerole_alias, description, vm_role) VALUES (4, NULL, 'Access Switch', 'access-switch', NULL, NULL);
INSERT INTO ref_devicerole (deviceroleid, netboxid, devicerole, devicerole_alias, description, vm_role) VALUES (5, NULL, 'Amplifier', 'amplifier', NULL, NULL);
INSERT INTO ref_devicerole (deviceroleid, netboxid, devicerole, devicerole_alias, description, vm_role) VALUES (6, NULL, 'Backbone Router', 'backbone-router', NULL, NULL);
INSERT INTO ref_devicerole (deviceroleid, netboxid, devicerole, devicerole_alias, description, vm_role) VALUES (7, NULL, 'BGM Player', 'bgm-player', NULL, NULL);
INSERT INTO ref_devicerole (deviceroleid, netboxid, devicerole, devicerole_alias, description, vm_role) VALUES (8, NULL, 'Border Router', 'border-router', NULL, NULL);
INSERT INTO ref_devicerole (deviceroleid, netboxid, devicerole, devicerole_alias, description, vm_role) VALUES (9, NULL, 'Building Management', 'building-management', NULL, NULL);
INSERT INTO ref_devicerole (deviceroleid, netboxid, devicerole, devicerole_alias, description, vm_role) VALUES (10, NULL, 'Camera', 'camera', NULL, NULL);
INSERT INTO ref_devicerole (deviceroleid, netboxid, devicerole, devicerole_alias, description, vm_role) VALUES (11, NULL, 'Channel Expander', 'channel-expander', NULL, NULL);
INSERT INTO ref_devicerole (deviceroleid, netboxid, devicerole, devicerole_alias, description, vm_role) VALUES (12, NULL, 'Codec', 'codec', NULL, NULL);
INSERT INTO ref_devicerole (deviceroleid, netboxid, devicerole, devicerole_alias, description, vm_role) VALUES (13, NULL, 'Computer', 'computer', NULL, NULL);
INSERT INTO ref_devicerole (deviceroleid, netboxid, devicerole, devicerole_alias, description, vm_role) VALUES (14, NULL, 'Conference Phone', 'conference-phone', NULL, NULL);
INSERT INTO ref_devicerole (deviceroleid, netboxid, devicerole, devicerole_alias, description, vm_role) VALUES (15, NULL, 'Console Server', 'console-server', NULL, NULL);
INSERT INTO ref_devicerole (deviceroleid, netboxid, devicerole, devicerole_alias, description, vm_role) VALUES (16, NULL, 'Control Panel', 'control-panel', NULL, NULL);
INSERT INTO ref_devicerole (deviceroleid, netboxid, devicerole, devicerole_alias, description, vm_role) VALUES (17, NULL, 'Core Switch', 'core-switch', NULL, NULL);
INSERT INTO ref_devicerole (deviceroleid, netboxid, devicerole, devicerole_alias, description, vm_role) VALUES (18, NULL, 'Digital Signage', 'digital-signage', NULL, NULL);
INSERT INTO ref_devicerole (deviceroleid, netboxid, devicerole, devicerole_alias, description, vm_role) VALUES (19, NULL, 'Distribution Switch', 'distribution-switch', NULL, NULL);
INSERT INTO ref_devicerole (deviceroleid, netboxid, devicerole, devicerole_alias, description, vm_role) VALUES (20, NULL, 'DSP', 'dsp', NULL, NULL);
INSERT INTO ref_devicerole (deviceroleid, netboxid, devicerole, devicerole_alias, description, vm_role) VALUES (21, NULL, 'Environmental monitor', 'environmental-monitor', NULL, NULL);
INSERT INTO ref_devicerole (deviceroleid, netboxid, devicerole, devicerole_alias, description, vm_role) VALUES (22, NULL, 'Firewall', 'firewall', NULL, NULL);
INSERT INTO ref_devicerole (deviceroleid, netboxid, devicerole, devicerole_alias, description, vm_role) VALUES (23, NULL, 'Gateway', 'gateway', NULL, NULL);
INSERT INTO ref_devicerole (deviceroleid, netboxid, devicerole, devicerole_alias, description, vm_role) VALUES (24, NULL, 'Hypervisor', 'hypervisor', NULL, NULL);
INSERT INTO ref_devicerole (deviceroleid, netboxid, devicerole, devicerole_alias, description, vm_role) VALUES (25, NULL, 'ISP Switch', 'isp-switch', NULL, NULL);
INSERT INTO ref_devicerole (deviceroleid, netboxid, devicerole, devicerole_alias, description, vm_role) VALUES (26, NULL, 'Microphone', 'microphone', NULL, NULL);
INSERT INTO ref_devicerole (deviceroleid, netboxid, devicerole, devicerole_alias, description, vm_role) VALUES (27, NULL, 'NAS', 'nas', NULL, NULL);
INSERT INTO ref_devicerole (deviceroleid, netboxid, devicerole, devicerole_alias, description, vm_role) VALUES (28, NULL, 'Patch Panel', 'patch-panel', NULL, NULL);
INSERT INTO ref_devicerole (deviceroleid, netboxid, devicerole, devicerole_alias, description, vm_role) VALUES (29, NULL, 'PDU', 'pdu', NULL, NULL);
INSERT INTO ref_devicerole (deviceroleid, netboxid, devicerole, devicerole_alias, description, vm_role) VALUES (30, NULL, 'Phone', 'phone', NULL, NULL);
INSERT INTO ref_devicerole (deviceroleid, netboxid, devicerole, devicerole_alias, description, vm_role) VALUES (31, NULL, 'Print Server', 'print server', NULL, NULL);
INSERT INTO ref_devicerole (deviceroleid, netboxid, devicerole, devicerole_alias, description, vm_role) VALUES (32, NULL, 'Printer', 'printer', NULL, NULL);
INSERT INTO ref_devicerole (deviceroleid, netboxid, devicerole, devicerole_alias, description, vm_role) VALUES (33, NULL, 'Projector', 'projector', NULL, NULL);
INSERT INTO ref_devicerole (deviceroleid, netboxid, devicerole, devicerole_alias, description, vm_role) VALUES (34, NULL, 'Remote Access Controller', 'remote-access-controller', NULL, NULL);
INSERT INTO ref_devicerole (deviceroleid, netboxid, devicerole, devicerole_alias, description, vm_role) VALUES (35, NULL, 'Room Controller', 'room-controller', NULL, NULL);
INSERT INTO ref_devicerole (deviceroleid, netboxid, devicerole, devicerole_alias, description, vm_role) VALUES (36, NULL, 'Router', 'router', NULL, NULL);
INSERT INTO ref_devicerole (deviceroleid, netboxid, devicerole, devicerole_alias, description, vm_role) VALUES (37, NULL, 'Screen Share', 'screen-share', NULL, NULL);
INSERT INTO ref_devicerole (deviceroleid, netboxid, devicerole, devicerole_alias, description, vm_role) VALUES (38, NULL, 'Server', 'server', NULL, NULL);
INSERT INTO ref_devicerole (deviceroleid, netboxid, devicerole, devicerole_alias, description, vm_role) VALUES (39, NULL, 'Server Blade', 'server-blade', NULL, NULL);
INSERT INTO ref_devicerole (deviceroleid, netboxid, devicerole, devicerole_alias, description, vm_role) VALUES (40, NULL, 'Server Blade Chassis', 'server-blade-chassis', NULL, NULL);
INSERT INTO ref_devicerole (deviceroleid, netboxid, devicerole, devicerole_alias, description, vm_role) VALUES (41, NULL, 'Supervisor', 'supervisor', NULL, NULL);
INSERT INTO ref_devicerole (deviceroleid, netboxid, devicerole, devicerole_alias, description, vm_role) VALUES (42, NULL, 'Switch', 'switch', NULL, NULL);
INSERT INTO ref_devicerole (deviceroleid, netboxid, devicerole, devicerole_alias, description, vm_role) VALUES (43, NULL, 'UPS', 'ups', NULL, NULL);
INSERT INTO ref_devicerole (deviceroleid, netboxid, devicerole, devicerole_alias, description, vm_role) VALUES (44, NULL, 'Video Switcher', 'video-switcher', NULL, NULL);
INSERT INTO ref_devicerole (deviceroleid, netboxid, devicerole, devicerole_alias, description, vm_role) VALUES (45, NULL, 'VMS', 'vms', NULL, NULL);
INSERT INTO ref_devicerole (deviceroleid, netboxid, devicerole, devicerole_alias, description, vm_role) VALUES (46, NULL, 'WAP', 'wap', NULL, NULL);
INSERT INTO ref_devicerole (deviceroleid, netboxid, devicerole, devicerole_alias, description, vm_role) VALUES (47, NULL, 'WLC', 'wlc', NULL, NULL);

INSERT INTO ref_platform (platformid, netboxid, platform, platform_alias, description, manufacturerid) VALUES (0, NULL, '', '', NULL, 0);
INSERT INTO ref_platform (platformid, netboxid, platform, platform_alias, description, manufacturerid) VALUES (1000, NULL, 'Undefined', 'undefined', NULL, 0);
INSERT INTO ref_platform (platformid, netboxid, platform, platform_alias, description, manufacturerid) SELECT 1, NULL, 'Arista EOS', 'arista-eos', NULL, manufacturerid FROM ref_manufacturer WHERE manufacturer_alias='arista';
INSERT INTO ref_platform (platformid, netboxid, platform, platform_alias, description, manufacturerid) SELECT 2, NULL, 'Brocade OS', 'brocade-os', NULL, manufacturerid FROM ref_manufacturer WHERE manufacturer_alias='brocade';
INSERT INTO ref_platform (platformid, netboxid, platform, platform_alias, description, manufacturerid) SELECT 3, NULL, 'Cisco IOS', 'cisco-ios', NULL, manufacturerid FROM ref_manufacturer WHERE manufacturer_alias='cisco';
INSERT INTO ref_platform (platformid, netboxid, platform, platform_alias, description, manufacturerid) SELECT 4, NULL, 'Cisco NX-OS', 'cisco-nx-os', NULL, manufacturerid FROM ref_manufacturer WHERE manufacturer_alias='cisco';
INSERT INTO ref_platform (platformid, netboxid, platform, platform_alias, description, manufacturerid) SELECT 5, NULL, 'ESXi Hypervisor', 'esxi-hypervisor', NULL, manufacturerid FROM ref_manufacturer WHERE manufacturer_alias='vmware';
INSERT INTO ref_platform (platformid, netboxid, platform, platform_alias, description, manufacturerid) SELECT 6, NULL, 'FortiOS', 'fortios', NULL, manufacturerid FROM ref_manufacturer WHERE manufacturer_alias='fortinet';
INSERT INTO ref_platform (platformid, netboxid, platform, platform_alias, description, manufacturerid) SELECT 7, NULL, 'Juniper Junos', 'juniper-junos', NULL,  manufacturerid FROM ref_manufacturer WHERE manufacturer_alias='juniper';
INSERT INTO ref_platform (platformid, netboxid, platform, platform_alias, description, manufacturerid) VALUES (8, NULL, 'Linux', 'linux', NULL, NULL);
INSERT INTO ref_platform (platformid, netboxid, platform, platform_alias, description, manufacturerid) SELECT 9, NULL, 'Windows', 'windows', NULL,  manufacturerid FROM ref_manufacturer WHERE manufacturer_alias='microsoft';

INSERT INTO ref_subdevice_role (subdevice_roleid, subdevice_role, subdevice_role_alias) VALUES (0, '', '');
INSERT INTO ref_subdevice_role (subdevice_roleid, subdevice_role, subdevice_role_alias) VALUES (1, 'Parent', 'parent');
INSERT INTO ref_subdevice_role (subdevice_roleid, subdevice_role, subdevice_role_alias) VALUES (2, 'Child', 'child');

INSERT INTO ref_devicetype (devicetypeid, netboxid, model, model_alias, manufacturerid, subdevice_roleid, part_number, u_height, is_full_depth, airflow, comments, parentid) VALUES (0, NULL, '', '', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO ref_devicetype (devicetypeid, netboxid, model, model_alias, manufacturerid, subdevice_roleid, part_number, u_height, is_full_depth, airflow, comments, parentid) VALUES (1000, NULL, 'Undefined', 'undefined', 1000, NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO ref_ipfamily (familyid, family) VALUES (1, 'IPv4');
INSERT INTO ref_ipfamily (familyid, family) VALUES (2, 'IPv6');

INSERT INTO ref_ipaddress_role (ipaddress_roleid, ipaddress_role) VALUES (1, 'Loopback');
INSERT INTO ref_ipaddress_role (ipaddress_roleid, ipaddress_role) VALUES (2, 'Secondary');

INSERT INTO ref_ipaddress_source (sourceid, description, tablename) VALUES (1, 'IP prefix from ref', 'ref_ipprefix');
INSERT INTO ref_ipaddress_source (sourceid, description, tablename) VALUES (2, 'IP range from ref', 'ref_iprange');
INSERT INTO ref_ipaddress_source (sourceid, description, tablename) VALUES (3, 'IP address from ref', 'ref_ipaddress');
INSERT INTO ref_ipaddress_source (sourceid, description, tablename) VALUES (4, 'Static IP address from ref', 'ref_static_device');

INSERT INTO ref_scan_ip_info (infoid, info) VALUES (1, 'snmp_community');
INSERT INTO ref_scan_ip_info (infoid, info) VALUES (2, 'ssh_username');
INSERT INTO ref_scan_ip_info (infoid, info) VALUES (3, 'ssh_password');
INSERT INTO ref_scan_ip_info (infoid, info) VALUES (4, 'telnet_username');
INSERT INTO ref_scan_ip_info (infoid, info) VALUES (5, 'telnet_password');
INSERT INTO ref_scan_ip_info (infoid, info) VALUES (6, 'name');
INSERT INTO ref_scan_ip_info (infoid, info) VALUES (7, 'hostname');
INSERT INTO ref_scan_ip_info (infoid, info) VALUES (8, 'description');
INSERT INTO ref_scan_ip_info (infoid, info) VALUES (9, 'eduid');
INSERT INTO ref_scan_ip_info (infoid, info) VALUES (10, 'activaireid');
INSERT INTO ref_scan_ip_info (infoid, info) VALUES (11, 'mac_internal');
INSERT INTO ref_scan_ip_info (infoid, info) VALUES (12, 'controller');
INSERT INTO ref_scan_ip_info (infoid, info) VALUES (13, 'macvendorid');

INSERT INTO ref_scan_snmp_oid (oidid, command, prescan, name, oid) VALUES (1, 'walk', FALSE, 'system', '.1.3.6.1.2.1.1');
INSERT INTO ref_scan_snmp_oid (oidid, command, prescan, name, oid) VALUES (2, 'walk', TRUE, 'ipNetToMediaPhysAddress', '.1.3.6.1.2.1.4.22.1.2');
INSERT INTO ref_scan_snmp_oid (oidid, command, prescan, name, oid) VALUES (3, 'walk', FALSE, 'dot1dTpFdbDestPortIfIndex', '.1.3.6.1.2.1.17.4.3.1.2');
INSERT INTO ref_scan_snmp_oid (oidid, command, prescan, name, oid) VALUES (4, 'walk', FALSE, 'ifIndex', '.1.3.6.1.2.1.2.2.1.1');
INSERT INTO ref_scan_snmp_oid (oidid, command, prescan, name, oid) VALUES (5, 'walk', FALSE, 'ifDescr', '.1.3.6.1.2.1.2.2.1.2');
INSERT INTO ref_scan_snmp_oid (oidid, command, prescan, name, oid) VALUES (6, 'walk', FALSE, 'ifAdminStatus', '.1.3.6.1.2.1.2.2.1.7');
INSERT INTO ref_scan_snmp_oid (oidid, command, prescan, name, oid) VALUES (7, 'walk', FALSE, 'ifOperStatus', '.1.3.6.1.2.1.2.2.1.8');
INSERT INTO ref_scan_snmp_oid (oidid, command, prescan, name, oid) VALUES (8, 'walk', FALSE, 'ifName', '.1.3.6.1.2.1.31.1.1.1.1');
INSERT INTO ref_scan_snmp_oid (oidid, command, prescan, name, oid) VALUES (9, 'walk', FALSE, 'ifAlias', '.1.3.6.1.2.1.31.1.1.1.18');
INSERT INTO ref_scan_snmp_oid (oidid, command, prescan, name, oid) VALUES (10, 'walk', FALSE, 'vtpVlanState', '.1.3.6.1.4.1.9.9.46.1.3.1.1.2');
INSERT INTO ref_scan_snmp_oid (oidid, command, prescan, name, oid) VALUES (11, 'get', FALSE, 'ipForwarding', '.1.3.6.1.2.1.4.1.0');
INSERT INTO ref_scan_snmp_oid (oidid, command, prescan, name, oid) VALUES (12, 'walk', FALSE, 'jnxJdhcpLocalServerBindingsMacAddress', '.1.3.6.1.4.1.2636.3.61.61.1.2.1.1.2');
INSERT INTO ref_scan_snmp_oid (oidid, command, prescan, name, oid) VALUES (13, 'walk', FALSE, 'lldpRemEntry', '.1.0.8802.1.1.2.1.4.1.1');
INSERT INTO ref_scan_snmp_oid (oidid, command, prescan, name, oid) VALUES (14, 'walk', FALSE, 'cdpCache', '.1.3.6.1.4.1.9.9.23.1.2');
INSERT INTO ref_scan_snmp_oid (oidid, command, prescan, name, oid) VALUES (15, 'walk', FALSE, 'bsnAPDot3MacAddress', '.1.3.6.1.4.1.14179.2.2.1.1.1');
INSERT INTO ref_scan_snmp_oid (oidid, command, prescan, name, oid) VALUES (16, 'walk', FALSE, 'bsnApIpAddress', '.1.3.6.1.4.1.14179.2.2.1.1.19');
INSERT INTO ref_scan_snmp_oid (oidid, command, prescan, name, oid) VALUES (17, 'walk', FALSE, 'bsnAPName', '.1.3.6.1.4.1.14179.2.2.1.1.3');
INSERT INTO ref_scan_snmp_oid (oidid, command, prescan, name, oid) VALUES (18, 'walk', FALSE, 'ruckusZDWLANAPMacAddr', '.1.3.6.1.4.1.25053.1.2.2.1.1.2.1.1.1');
INSERT INTO ref_scan_snmp_oid (oidid, command, prescan, name, oid) VALUES (19, 'walk', FALSE, 'ruckusZDWLANAPIPAddr', '.1.3.6.1.4.1.25053.1.2.2.1.1.2.1.1.10');
INSERT INTO ref_scan_snmp_oid (oidid, command, prescan, name, oid) VALUES (20, 'walk', FALSE, 'ruckusZDWLANAPDescription', '.1.3.6.1.4.1.25053.1.2.2.1.1.2.1.1.2');
INSERT INTO ref_scan_snmp_oid (oidid, command, prescan, name, oid) VALUES (21, 'walk', FALSE, 'ruckusSCGAPMac', '.1.3.6.1.4.1.25053.1.3.2.1.1.2.2.1.1');
INSERT INTO ref_scan_snmp_oid (oidid, command, prescan, name, oid) VALUES (22, 'walk', FALSE, 'ruckusSCGAPIp', '.1.3.6.1.4.1.25053.1.3.2.1.1.2.2.1.10');
INSERT INTO ref_scan_snmp_oid (oidid, command, prescan, name, oid) VALUES (23, 'walk', FALSE, 'ruckusSCGAPName', '.1.3.6.1.4.1.25053.1.3.2.1.1.2.2.1.5');
INSERT INTO ref_scan_snmp_oid (oidid, command, prescan, name, oid) VALUES (24, 'walk', FALSE, 'dot1dBasePortIfIndex', '1.3.6.1.2.1.17.1.4.1.2');
INSERT INTO ref_scan_snmp_oid (oidid, command, prescan, name, oid) VALUES (25, 'walk', FALSE, 'ifPhysAddress', '.1.3.6.1.2.1.2.2.1.6');
INSERT INTO ref_scan_snmp_oid (oidid, command, prescan, name, oid) VALUES (28, 'get', FALSE, 'ipCidrRouteNumber', '.1.3.6.1.2.1.4.24.3.0');
INSERT INTO ref_scan_snmp_oid (oidid, command, prescan, name, oid) VALUES (29, 'walk', FALSE, 'ipAddrTable', '.1.3.6.1.2.1.4.20');
INSERT INTO ref_scan_snmp_oid (oidid, command, prescan, name, oid) VALUES (33, 'walk', FALSE, 'dot1qVlanStatus', '.1.3.6.1.2.1.17.7.1.4.2.1.6');

INSERT INTO ref_static_device (deviceid, ip, active, snmp_community) VALUES (1, '52.9.8.62', TRUE, NULL);

INSERT INTO ref_wlc_type (wlcid, wlc_type, wlc_name) VALUES (1, 'mist', 'MIST Controller');
INSERT INTO ref_wlc_type (wlcid, wlc_type, wlc_name) VALUES (2, 'cisco_wlc', 'Cisco WLC');
INSERT INTO ref_wlc_type (wlcid, wlc_type, wlc_name) VALUES (3, 'ruckus_zd_wlc', 'Ruckus ZD WLC');
INSERT INTO ref_wlc_type (wlcid, wlc_type, wlc_name) VALUES (4, 'ruckus_scg_wlc', 'Ruckus SCG WLC');
INSERT INTO ref_wlc_type (wlcid, wlc_type, wlc_name) VALUES (5, 'ruckus_sz_wlc', 'Ruckus SZ WLC');

INSERT INTO ref_mac_manufacturer_map (organization , manufacturerid) SELECT LOWER('panasonic communications co., ltd.'), manufacturerid FROM ref_manufacturer WHERE LOWER(manufacturer_alias) ='panasonic';
INSERT INTO ref_mac_manufacturer_map (organization , manufacturerid) SELECT LOWER('ruckus wireless'), manufacturerid FROM ref_manufacturer WHERE LOWER(manufacturer_alias) ='ruckus';
INSERT INTO ref_mac_manufacturer_map (organization , manufacturerid) SELECT LOWER('juniper networks'), manufacturerid FROM ref_manufacturer WHERE LOWER(manufacturer_alias) ='juniper';
INSERT INTO ref_mac_manufacturer_map (organization , manufacturerid) SELECT LOWER('advidia'), manufacturerid FROM ref_manufacturer WHERE LOWER(manufacturer_alias) ='advidia';
INSERT INTO ref_mac_manufacturer_map (organization , manufacturerid) SELECT LOWER('inforce computing inc.'), manufacturerid FROM ref_manufacturer WHERE LOWER(manufacturer_alias) ='inforce';
INSERT INTO ref_mac_manufacturer_map (organization , manufacturerid) SELECT LOWER('panasonic corporation connected solutions company'), manufacturerid FROM ref_manufacturer WHERE LOWER(manufacturer_alias) ='panasonic';
INSERT INTO ref_mac_manufacturer_map (organization , manufacturerid) SELECT LOWER('cisco systems, inc'), manufacturerid FROM ref_manufacturer WHERE LOWER(manufacturer_alias) ='cisco';
INSERT INTO ref_mac_manufacturer_map (organization , manufacturerid) SELECT LOWER('texas instruments'), manufacturerid FROM ref_manufacturer WHERE LOWER(manufacturer_alias) ='ti';
INSERT INTO ref_mac_manufacturer_map (organization , manufacturerid) SELECT LOWER('mist systems, inc.'), manufacturerid FROM ref_manufacturer WHERE LOWER(manufacturer_alias) ='juniper';
INSERT INTO ref_mac_manufacturer_map (organization , manufacturerid) SELECT LOWER('hewlett packard'), manufacturerid FROM ref_manufacturer WHERE LOWER(manufacturer_alias) ='hp';
INSERT INTO ref_mac_manufacturer_map (organization , manufacturerid) SELECT LOWER('eaton corporation'), manufacturerid FROM ref_manufacturer WHERE LOWER(manufacturer_alias) ='eaton';
INSERT INTO ref_mac_manufacturer_map (organization , manufacturerid) SELECT LOWER('rtx telecom a/s'), manufacturerid FROM ref_manufacturer WHERE LOWER(manufacturer_alias) ='rtx-telecom';
INSERT INTO ref_mac_manufacturer_map (organization , manufacturerid) SELECT LOWER('obihai technology, inc.'), manufacturerid FROM ref_manufacturer WHERE LOWER(manufacturer_alias) ='obihai';
INSERT INTO ref_mac_manufacturer_map (organization , manufacturerid) SELECT LOWER('apple, inc.'), manufacturerid FROM ref_manufacturer WHERE LOWER(manufacturer_alias) ='apple';
INSERT INTO ref_mac_manufacturer_map (organization , manufacturerid) SELECT LOWER('qsc llc'), manufacturerid FROM ref_manufacturer WHERE LOWER(manufacturer_alias) ='qsc';
INSERT INTO ref_mac_manufacturer_map (organization , manufacturerid) SELECT LOWER('nvidia'), manufacturerid FROM ref_manufacturer WHERE LOWER(manufacturer_alias) ='nvidia';
INSERT INTO ref_mac_manufacturer_map (organization , manufacturerid) SELECT LOWER('dell inc.'), manufacturerid FROM ref_manufacturer WHERE LOWER(manufacturer_alias) ='dell';
INSERT INTO ref_mac_manufacturer_map (organization , manufacturerid) SELECT LOWER('axis communications ab'), manufacturerid FROM ref_manufacturer WHERE LOWER(manufacturer_alias) ='axis';
INSERT INTO ref_mac_manufacturer_map (organization , manufacturerid) SELECT LOWER('3par data'), manufacturerid FROM ref_manufacturer WHERE LOWER(manufacturer_alias) ='3par-data';
INSERT INTO ref_mac_manufacturer_map (organization , manufacturerid) SELECT LOWER('wibrain'), manufacturerid FROM ref_manufacturer WHERE LOWER(manufacturer_alias) ='wibrain';
INSERT INTO ref_mac_manufacturer_map (organization , manufacturerid) SELECT LOWER('brocade communications systems llc'), manufacturerid FROM ref_manufacturer WHERE LOWER(manufacturer_alias) ='brocade';
INSERT INTO ref_mac_manufacturer_map (organization , manufacturerid) SELECT LOWER('crestron electronics, inc.'), manufacturerid FROM ref_manufacturer WHERE LOWER(manufacturer_alias) ='crestron';
INSERT INTO ref_mac_manufacturer_map (organization , manufacturerid) SELECT LOWER('polycom'), manufacturerid FROM ref_manufacturer WHERE LOWER(manufacturer_alias) ='polycom';
INSERT INTO ref_mac_manufacturer_map (organization , manufacturerid) SELECT LOWER('mercury security corporation'), manufacturerid FROM ref_manufacturer WHERE LOWER(manufacturer_alias) ='mercury-security';
INSERT INTO ref_mac_manufacturer_map (organization , manufacturerid) SELECT LOWER('minix technology limited'), manufacturerid FROM ref_manufacturer WHERE LOWER(manufacturer_alias) ='minix';
INSERT INTO ref_mac_manufacturer_map (organization , manufacturerid) SELECT LOWER('ashly audio, inc.'), manufacturerid FROM ref_manufacturer WHERE LOWER(manufacturer_alias) ='ashly';
INSERT INTO ref_mac_manufacturer_map (organization , manufacturerid) SELECT LOWER('intel corporate'), manufacturerid FROM ref_manufacturer WHERE LOWER(manufacturer_alias) ='intel';
INSERT INTO ref_mac_manufacturer_map (organization , manufacturerid) SELECT LOWER('giga-byte technology co.,ltd.'), manufacturerid FROM ref_manufacturer WHERE LOWER(manufacturer_alias) ='gigabyte';
INSERT INTO ref_mac_manufacturer_map (organization , manufacturerid) SELECT LOWER('microchip technology inc.'), manufacturerid FROM ref_manufacturer WHERE LOWER(manufacturer_alias) ='microchip';
INSERT INTO ref_mac_manufacturer_map (organization , manufacturerid) SELECT LOWER('nec corporation'), manufacturerid FROM ref_manufacturer WHERE LOWER(manufacturer_alias) ='nec';
INSERT INTO ref_mac_manufacturer_map (organization , manufacturerid) SELECT LOWER('hewlett packard enterprise'), manufacturerid FROM ref_manufacturer WHERE LOWER(manufacturer_alias) ='hp';
INSERT INTO ref_mac_manufacturer_map (organization , manufacturerid) SELECT LOWER('cisco meraki'), manufacturerid FROM ref_manufacturer WHERE LOWER(manufacturer_alias) ='cisco';
INSERT INTO ref_mac_manufacturer_map (organization , manufacturerid) SELECT LOWER('hp inc.'), manufacturerid FROM ref_manufacturer WHERE LOWER(manufacturer_alias) ='hp';
INSERT INTO ref_mac_manufacturer_map (organization , manufacturerid) SELECT LOWER('neatframe as'), manufacturerid FROM ref_manufacturer WHERE LOWER(manufacturer_alias) ='neatframe';
INSERT INTO ref_mac_manufacturer_map (organization , manufacturerid) SELECT LOWER('yealink(xiamen) network technology co.,ltd.'), manufacturerid FROM ref_manufacturer WHERE LOWER(manufacturer_alias) ='yealink';
INSERT INTO ref_mac_manufacturer_map (organization , manufacturerid) SELECT LOWER('panasonic i-pro sensing solutions co., ltd.'), manufacturerid FROM ref_manufacturer WHERE LOWER(manufacturer_alias) ='panasonic';
INSERT INTO ref_mac_manufacturer_map (organization , manufacturerid) SELECT LOWER('ampak technology, inc.'), manufacturerid FROM ref_manufacturer WHERE LOWER(manufacturer_alias) ='ampak';
INSERT INTO ref_mac_manufacturer_map (organization , manufacturerid) SELECT LOWER('viavideo communications, inc.'), manufacturerid FROM ref_manufacturer WHERE LOWER(manufacturer_alias) ='viavideo';
INSERT INTO ref_mac_manufacturer_map (organization , manufacturerid) SELECT LOWER('multitech systems, inc.'), manufacturerid FROM ref_manufacturer WHERE LOWER(manufacturer_alias) ='multitech';
INSERT INTO ref_mac_manufacturer_map (organization , manufacturerid) SELECT LOWER('shure incorporated'), manufacturerid FROM ref_manufacturer WHERE LOWER(manufacturer_alias) ='shure';
INSERT INTO ref_mac_manufacturer_map (organization , manufacturerid) SELECT LOWER('samsung electronics co.,ltd'), manufacturerid FROM ref_manufacturer WHERE LOWER(manufacturer_alias) ='samsung';
INSERT INTO ref_mac_manufacturer_map (organization , manufacturerid) SELECT LOWER('espressif inc.'), manufacturerid FROM ref_manufacturer WHERE LOWER(manufacturer_alias) ='espressif';
INSERT INTO ref_mac_manufacturer_map (organization , manufacturerid) SELECT LOWER('fortinet, inc.'), manufacturerid FROM ref_manufacturer WHERE LOWER(manufacturer_alias) ='fortinet';
INSERT INTO ref_mac_manufacturer_map (organization , manufacturerid) SELECT LOWER('aiphone co.,ltd'), manufacturerid FROM ref_manufacturer WHERE LOWER(manufacturer_alias) ='aiphone';
INSERT INTO ref_mac_manufacturer_map (organization , manufacturerid) SELECT LOWER('opengear, inc'), manufacturerid FROM ref_manufacturer WHERE LOWER(manufacturer_alias) ='opengear';
INSERT INTO ref_mac_manufacturer_map (organization , manufacturerid) SELECT LOWER('seiko epson corporation'), manufacturerid FROM ref_manufacturer WHERE LOWER(manufacturer_alias) ='epson';
INSERT INTO ref_mac_manufacturer_map (organization , manufacturerid) SELECT LOWER('2n telekomunikace a.s.'), manufacturerid FROM ref_manufacturer WHERE LOWER(manufacturer_alias) ='2n-telekomunikace';
INSERT INTO ref_mac_manufacturer_map (organization , manufacturerid) SELECT LOWER('lg electronics'), manufacturerid FROM ref_manufacturer WHERE LOWER(manufacturer_alias) ='lg';
INSERT INTO ref_mac_manufacturer_map (organization , manufacturerid) SELECT LOWER('vmware, inc.'), manufacturerid FROM ref_manufacturer WHERE LOWER(manufacturer_alias) ='vmware';
INSERT INTO ref_mac_manufacturer_map (organization , manufacturerid) SELECT LOWER('belkin international inc.'), manufacturerid FROM ref_manufacturer WHERE LOWER(manufacturer_alias) ='belkin';
INSERT INTO ref_mac_manufacturer_map (organization , manufacturerid) SELECT LOWER('pcs systemtechnik gmbh'), manufacturerid FROM ref_manufacturer WHERE LOWER(manufacturer_alias) ='pcs-systemtechnik';
INSERT INTO ref_mac_manufacturer_map (organization , manufacturerid) SELECT LOWER('quanta computer inc.'), manufacturerid FROM ref_manufacturer WHERE LOWER(manufacturer_alias) ='quanta';
INSERT INTO ref_mac_manufacturer_map (organization , manufacturerid) SELECT LOWER('super micro computer, inc.'), manufacturerid FROM ref_manufacturer WHERE LOWER(manufacturer_alias) ='super-micro';
INSERT INTO ref_mac_manufacturer_map (organization , manufacturerid) SELECT LOWER('sonicwall'), manufacturerid FROM ref_manufacturer WHERE LOWER(manufacturer_alias) ='sonicwall';
INSERT INTO ref_mac_manufacturer_map (organization , manufacturerid) SELECT LOWER('amazon technologies inc.'), manufacturerid FROM ref_manufacturer WHERE LOWER(manufacturer_alias) ='amazon';
INSERT INTO ref_mac_manufacturer_map (organization , manufacturerid) SELECT LOWER('palo alto networks'), manufacturerid FROM ref_manufacturer WHERE LOWER(manufacturer_alias) ='palo-alto';
INSERT INTO ref_mac_manufacturer_map (organization , manufacturerid) SELECT LOWER('biamp systems'), manufacturerid FROM ref_manufacturer WHERE LOWER(manufacturer_alias) ='biamp';
INSERT INTO ref_mac_manufacturer_map (organization , manufacturerid) SELECT LOWER('logitech'), manufacturerid FROM ref_manufacturer WHERE LOWER(manufacturer_alias) ='logitech';
INSERT INTO ref_mac_manufacturer_map (organization , manufacturerid) SELECT LOWER('s2 security corporation'), manufacturerid FROM ref_manufacturer WHERE LOWER(manufacturer_alias) ='s2-security';
INSERT INTO ref_mac_manufacturer_map (organization , manufacturerid) SELECT LOWER('vcs video communication systems ag'), manufacturerid FROM ref_manufacturer WHERE LOWER(manufacturer_alias) ='vcs';
INSERT INTO ref_mac_manufacturer_map (organization , manufacturerid) SELECT LOWER('apc by schneider electric'), manufacturerid FROM ref_manufacturer WHERE LOWER(manufacturer_alias) ='apc';
INSERT INTO ref_mac_manufacturer_map (organization , manufacturerid) SELECT LOWER('sonos, inc.'), manufacturerid FROM ref_manufacturer WHERE LOWER(manufacturer_alias) ='sonos';
INSERT INTO ref_mac_manufacturer_map (organization , manufacturerid) SELECT LOWER('innosys, inc.'), manufacturerid FROM ref_manufacturer WHERE LOWER(manufacturer_alias) ='innosys';
INSERT INTO ref_mac_manufacturer_map (organization , manufacturerid) SELECT LOWER('google, inc.'), manufacturerid FROM ref_manufacturer WHERE LOWER(manufacturer_alias) ='google';
INSERT INTO ref_mac_manufacturer_map (organization , manufacturerid) SELECT LOWER('netgear'), manufacturerid FROM ref_manufacturer WHERE LOWER(manufacturer_alias) ='netgear';
INSERT INTO ref_mac_manufacturer_map (organization , manufacturerid) SELECT LOWER('nokia'), manufacturerid FROM ref_manufacturer WHERE LOWER(manufacturer_alias) ='nokia';
INSERT INTO ref_mac_manufacturer_map (organization , manufacturerid) SELECT LOWER('ubiquiti networks inc.'), manufacturerid FROM ref_manufacturer WHERE LOWER(manufacturer_alias) ='ubiquiti';
INSERT INTO ref_mac_manufacturer_map (organization , manufacturerid) SELECT LOWER('audinate pty l'), manufacturerid FROM ref_manufacturer WHERE LOWER(manufacturer_alias) ='audinate';
INSERT INTO ref_mac_manufacturer_map (organization , manufacturerid) SELECT LOWER('grandstream networks, inc.'), manufacturerid FROM ref_manufacturer WHERE LOWER(manufacturer_alias) ='grandstream';
INSERT INTO ref_mac_manufacturer_map (organization , manufacturerid) SELECT LOWER('raspberry pi trading ltd'), manufacturerid FROM ref_manufacturer WHERE LOWER(manufacturer_alias) ='raspberry-pi';
INSERT INTO ref_mac_manufacturer_map (organization , manufacturerid) SELECT LOWER('asustek computer inc.'), manufacturerid FROM ref_manufacturer WHERE LOWER(manufacturer_alias) ='asustek';
INSERT INTO ref_mac_manufacturer_map (organization , manufacturerid) SELECT LOWER('tp-link technologies co.,ltd.'), manufacturerid FROM ref_manufacturer WHERE LOWER(manufacturer_alias) ='tp-link';
INSERT INTO ref_mac_manufacturer_map (organization , manufacturerid) SELECT LOWER('fortinet inc.'), manufacturerid FROM ref_manufacturer WHERE LOWER(manufacturer_alias) ='fortinet';
INSERT INTO ref_mac_manufacturer_map (organization , manufacturerid) SELECT LOWER('extron electronics'), manufacturerid FROM ref_manufacturer WHERE LOWER(manufacturer_alias) ='extron';
INSERT INTO ref_mac_manufacturer_map (organization , manufacturerid) SELECT LOWER('hitachi maxell, ltd., optronics division'), manufacturerid FROM ref_manufacturer WHERE LOWER(manufacturer_alias) ='hitachi';
INSERT INTO ref_mac_manufacturer_map (organization , manufacturerid) SELECT LOWER('liteon'), manufacturerid FROM ref_manufacturer WHERE LOWER(manufacturer_alias) ='liteon';
INSERT INTO ref_mac_manufacturer_map (organization , manufacturerid) SELECT LOWER('canon inc.'), manufacturerid FROM ref_manufacturer WHERE LOWER(manufacturer_alias) ='canon';
INSERT INTO ref_mac_manufacturer_map (organization , manufacturerid) SELECT LOWER('sophos ltd'), manufacturerid FROM ref_manufacturer WHERE LOWER(manufacturer_alias) ='sophos';
INSERT INTO ref_mac_manufacturer_map (organization , manufacturerid) SELECT LOWER('routerboard.com'), manufacturerid FROM ref_manufacturer WHERE LOWER(manufacturer_alias) ='mikrotik';
INSERT INTO ref_mac_manufacturer_map (organization , manufacturerid) SELECT LOWER('aruba, a hewlett packard enterprise company'), manufacturerid FROM ref_manufacturer WHERE LOWER(manufacturer_alias) ='aruba';
INSERT INTO ref_mac_manufacturer_map (organization , manufacturerid) SELECT LOWER('huawei technologies co.,ltd'), manufacturerid FROM ref_manufacturer WHERE LOWER(manufacturer_alias) ='huawei';
INSERT INTO ref_mac_manufacturer_map (organization , manufacturerid) SELECT LOWER('alcatel-lucent ipd'), manufacturerid FROM ref_manufacturer WHERE LOWER(manufacturer_alias) ='alcatel-lucent';
INSERT INTO ref_mac_manufacturer_map (organization , manufacturerid) SELECT LOWER('realtek semiconductor corp.'), manufacturerid FROM ref_manufacturer WHERE LOWER(manufacturer_alias) ='realtek';
INSERT INTO ref_mac_manufacturer_map (organization , manufacturerid) SELECT LOWER('lantronix'), manufacturerid FROM ref_manufacturer WHERE LOWER(manufacturer_alias) ='lantronix';
INSERT INTO ref_mac_manufacturer_map (organization , manufacturerid) SELECT LOWER('sony corporation'), manufacturerid FROM ref_manufacturer WHERE LOWER(manufacturer_alias) ='sony';
INSERT INTO ref_mac_manufacturer_map (organization , manufacturerid) SELECT LOWER('dolby laboratories, inc.'), manufacturerid FROM ref_manufacturer WHERE LOWER(manufacturer_alias) ='sony';
INSERT INTO ref_mac_manufacturer_map (organization , manufacturerid) SELECT LOWER('raspberry pi foundation'), manufacturerid FROM ref_manufacturer WHERE LOWER(manufacturer_alias) ='raspberry-pi';
INSERT INTO ref_mac_manufacturer_map (organization , manufacturerid) SELECT LOWER('tp-link corporation limited'), manufacturerid FROM ref_manufacturer WHERE LOWER(manufacturer_alias) ='tp-link';
INSERT INTO ref_mac_manufacturer_map (organization , manufacturerid) SELECT LOWER('microsoft corporation'), manufacturerid FROM ref_manufacturer WHERE LOWER(manufacturer_alias) ='microsoft';
INSERT INTO ref_mac_manufacturer_map (organization , manufacturerid) SELECT LOWER('avaya inc'), manufacturerid FROM ref_manufacturer WHERE LOWER(manufacturer_alias) ='avaya';
INSERT INTO ref_mac_manufacturer_map (organization , manufacturerid) SELECT LOWER('wistron infocomm (zhongshan) corporation'), manufacturerid FROM ref_manufacturer WHERE LOWER(manufacturer_alias) ='wistron';
INSERT INTO ref_mac_manufacturer_map (organization , manufacturerid) SELECT LOWER('brother industries, ltd.'), manufacturerid FROM ref_manufacturer WHERE LOWER(manufacturer_alias) ='brother';
INSERT INTO ref_mac_manufacturer_map (organization , manufacturerid) SELECT LOWER('asix electronics corp.'), manufacturerid FROM ref_manufacturer WHERE LOWER(manufacturer_alias) ='asix';
INSERT INTO ref_mac_manufacturer_map (organization , manufacturerid) SELECT LOWER('zyxel communications corporation'), manufacturerid FROM ref_manufacturer WHERE LOWER(manufacturer_alias) ='zyxel';
INSERT INTO ref_mac_manufacturer_map (organization , manufacturerid) SELECT LOWER('ricoh company, ltd.'), manufacturerid FROM ref_manufacturer WHERE LOWER(manufacturer_alias) ='ricoh';
INSERT INTO ref_mac_manufacturer_map (organization , manufacturerid) SELECT LOWER('xerox corporation'), manufacturerid FROM ref_manufacturer WHERE LOWER(manufacturer_alias) ='xerox';
INSERT INTO ref_mac_manufacturer_map (organization , manufacturerid) SELECT LOWER('nintendo co.,ltd'), manufacturerid FROM ref_manufacturer WHERE LOWER(manufacturer_alias) ='nintendo';
INSERT INTO ref_mac_manufacturer_map (organization , manufacturerid) SELECT LOWER('cisco-linksys, llc'), manufacturerid FROM ref_manufacturer WHERE LOWER(manufacturer_alias) ='linksys';
INSERT INTO ref_mac_manufacturer_map (organization , manufacturerid) SELECT LOWER('xiaomi communications co ltd'), manufacturerid FROM ref_manufacturer WHERE LOWER(manufacturer_alias) ='xiaomi';
INSERT INTO ref_mac_manufacturer_map (organization , manufacturerid) SELECT LOWER('kyocera display corporation'), manufacturerid FROM ref_manufacturer WHERE LOWER(manufacturer_alias) ='kyocera';
INSERT INTO ref_mac_manufacturer_map (organization , manufacturerid) SELECT LOWER('samsung electro mechanics co., ltd.'), manufacturerid FROM ref_manufacturer WHERE LOWER(manufacturer_alias) ='samsung';
INSERT INTO ref_mac_manufacturer_map (organization , manufacturerid) SELECT LOWER('lg electronics inc'), manufacturerid FROM ref_manufacturer WHERE LOWER(manufacturer_alias) ='lg';
INSERT INTO ref_mac_manufacturer_map (organization , manufacturerid) SELECT LOWER('qnap systems, inc.'), manufacturerid FROM ref_manufacturer WHERE LOWER(manufacturer_alias) ='qnap';
INSERT INTO ref_mac_manufacturer_map (organization , manufacturerid) SELECT LOWER('vantage controls'), manufacturerid FROM ref_manufacturer WHERE LOWER(manufacturer_alias) ='vantage';
INSERT INTO ref_mac_manufacturer_map (organization , manufacturerid) SELECT LOWER('sony visual products inc.'), manufacturerid FROM ref_manufacturer WHERE LOWER(manufacturer_alias) ='sony';
INSERT INTO ref_mac_manufacturer_map (organization , manufacturerid) SELECT LOWER('samsung techwin co.,ltd'), manufacturerid FROM ref_manufacturer WHERE LOWER(manufacturer_alias) ='samsung';
INSERT INTO ref_mac_manufacturer_map (organization , manufacturerid) SELECT LOWER('american power conversion corp'), manufacturerid FROM ref_manufacturer WHERE LOWER(manufacturer_alias) ='apc';
INSERT INTO ref_mac_manufacturer_map (organization , manufacturerid) SELECT LOWER('lexmark international, inc.'), manufacturerid FROM ref_manufacturer WHERE LOWER(manufacturer_alias) ='lexmark';
INSERT INTO ref_mac_manufacturer_map (organization , manufacturerid) SELECT LOWER('liteon technology corporation'), manufacturerid FROM ref_manufacturer WHERE LOWER(manufacturer_alias) ='liteon';
INSERT INTO ref_mac_manufacturer_map (organization , manufacturerid) SELECT LOWER('draytek corp.'), manufacturerid FROM ref_manufacturer WHERE LOWER(manufacturer_alias) ='draytek';
INSERT INTO ref_mac_manufacturer_map (organization , manufacturerid) SELECT LOWER('lg innotek'), manufacturerid FROM ref_manufacturer WHERE LOWER(manufacturer_alias) ='lg';
INSERT INTO ref_mac_manufacturer_map (organization , manufacturerid) SELECT LOWER('panasonic corporation avc networks company'), manufacturerid FROM ref_manufacturer WHERE LOWER(manufacturer_alias) ='panasonic';
INSERT INTO ref_mac_manufacturer_map (organization , manufacturerid) SELECT LOWER('ricoh company,ltd.'), manufacturerid FROM ref_manufacturer WHERE LOWER(manufacturer_alias) ='ricoh';
INSERT INTO ref_mac_manufacturer_map (organization , manufacturerid) SELECT LOWER('mitsubishi electric corporation'), manufacturerid FROM ref_manufacturer WHERE LOWER(manufacturer_alias) ='mitsubishi';
INSERT INTO ref_mac_manufacturer_map (organization , manufacturerid) SELECT LOWER('western digital corporation'), manufacturerid FROM ref_manufacturer WHERE LOWER(manufacturer_alias) ='wd';
INSERT INTO ref_mac_manufacturer_map (organization , manufacturerid) SELECT LOWER('lg electronics (mobile communications)'), manufacturerid FROM ref_manufacturer WHERE LOWER(manufacturer_alias) ='lg';
INSERT INTO ref_mac_manufacturer_map (organization , manufacturerid) SELECT LOWER('cisco spvtg'), manufacturerid FROM ref_manufacturer WHERE LOWER(manufacturer_alias) ='cisco';
INSERT INTO ref_mac_manufacturer_map (organization , manufacturerid) SELECT LOWER('moxa technologies corp., ltd.'), manufacturerid FROM ref_manufacturer WHERE LOWER(manufacturer_alias) ='moxa';
INSERT INTO ref_mac_manufacturer_map (organization , manufacturerid) SELECT LOWER('motorola mobility llc, a lenovo company'), manufacturerid FROM ref_manufacturer WHERE LOWER(manufacturer_alias) ='motorola';
INSERT INTO ref_mac_manufacturer_map (organization , manufacturerid) SELECT LOWER('digium'), manufacturerid FROM ref_manufacturer WHERE LOWER(manufacturer_alias) ='digium';
INSERT INTO ref_mac_manufacturer_map (organization , manufacturerid) SELECT LOWER('lifesize communications, inc'), manufacturerid FROM ref_manufacturer WHERE LOWER(manufacturer_alias) ='lifesize';
INSERT INTO ref_mac_manufacturer_map (organization , manufacturerid) SELECT LOWER('d-link international'), manufacturerid FROM ref_manufacturer WHERE LOWER(manufacturer_alias) ='d-link';
INSERT INTO ref_mac_manufacturer_map (organization , manufacturerid) SELECT LOWER('fujifilm business innovation corp.'), manufacturerid FROM ref_manufacturer WHERE LOWER(manufacturer_alias) ='fujifilm';
INSERT INTO ref_mac_manufacturer_map (organization , manufacturerid) SELECT LOWER('konica minolta holdings, inc.'), manufacturerid FROM ref_manufacturer WHERE LOWER(manufacturer_alias) ='konica-minolta';
INSERT INTO ref_mac_manufacturer_map (organization , manufacturerid) SELECT LOWER('sharp corporation'), manufacturerid FROM ref_manufacturer WHERE LOWER(manufacturer_alias) ='sharp';
INSERT INTO ref_mac_manufacturer_map (organization , manufacturerid) SELECT LOWER('huawei device co., ltd.'), manufacturerid FROM ref_manufacturer WHERE LOWER(manufacturer_alias) ='huawei';
INSERT INTO ref_mac_manufacturer_map (organization , manufacturerid) SELECT LOWER('western digital'), manufacturerid FROM ref_manufacturer WHERE LOWER(manufacturer_alias) ='wd';
INSERT INTO ref_mac_manufacturer_map (organization , manufacturerid) SELECT LOWER('ibm corp'), manufacturerid FROM ref_manufacturer WHERE LOWER(manufacturer_alias) ='ibm';
INSERT INTO ref_mac_manufacturer_map (organization , manufacturerid) SELECT LOWER('microsoft'), manufacturerid FROM ref_manufacturer WHERE LOWER(manufacturer_alias) ='microsoft';
INSERT INTO ref_mac_manufacturer_map (organization , manufacturerid) SELECT LOWER('broadcom limited'), manufacturerid FROM ref_manufacturer WHERE LOWER(manufacturer_alias) ='broadcom';
INSERT INTO ref_mac_manufacturer_map (organization , manufacturerid) SELECT LOWER('nec platforms, ltd'), manufacturerid FROM ref_manufacturer WHERE LOWER(manufacturer_alias) ='nec';
INSERT INTO ref_mac_manufacturer_map (organization , manufacturerid) SELECT LOWER('qlogic corporation'), manufacturerid FROM ref_manufacturer WHERE LOWER(manufacturer_alias) ='qlogic';
INSERT INTO ref_mac_manufacturer_map (organization , manufacturerid) SELECT LOWER('absolute acoustics'), manufacturerid FROM ref_manufacturer WHERE LOWER(manufacturer_alias) ='absolute-acoustics';
INSERT INTO ref_mac_manufacturer_map (organization , manufacturerid) SELECT LOWER('parallels, inc.'), manufacturerid FROM ref_manufacturer WHERE LOWER(manufacturer_alias) ='parallels';
INSERT INTO ref_mac_manufacturer_map (organization , manufacturerid) SELECT LOWER('zte corporation'), manufacturerid FROM ref_manufacturer WHERE LOWER(manufacturer_alias) ='zte';
INSERT INTO ref_mac_manufacturer_map (organization , manufacturerid) SELECT LOWER('motorola (wuhan) mobility technologies communication co., ltd.'), manufacturerid FROM ref_manufacturer WHERE LOWER(manufacturer_alias) ='motorola';
INSERT INTO ref_mac_manufacturer_map (organization , manufacturerid) SELECT LOWER('dell emc'), manufacturerid FROM ref_manufacturer WHERE LOWER(manufacturer_alias) ='emc';
INSERT INTO ref_mac_manufacturer_map (organization , manufacturerid) SELECT LOWER('fujitsu technology solutions gmbh'), manufacturerid FROM ref_manufacturer WHERE LOWER(manufacturer_alias) ='fujitsu';
INSERT INTO ref_mac_manufacturer_map (organization , manufacturerid) SELECT LOWER('inpro comm'), manufacturerid FROM ref_manufacturer WHERE LOWER(manufacturer_alias) ='inpro';
INSERT INTO ref_mac_manufacturer_map (organization , manufacturerid) SELECT LOWER('hitachi,ltd.'), manufacturerid FROM ref_manufacturer WHERE LOWER(manufacturer_alias) ='hitachi';
INSERT INTO ref_mac_manufacturer_map (organization , manufacturerid) SELECT LOWER('bose corporation'), manufacturerid FROM ref_manufacturer WHERE LOWER(manufacturer_alias) ='bose';

INSERT INTO ref_nnml_input_type (typeid, input_type, description) VALUES (1, 'ip_bits', 'bits in ip address');
INSERT INTO ref_nnml_input_type (typeid, input_type, description) VALUES (2, 'macvendorid', 'assignmentid field of info_mac table');
INSERT INTO ref_nnml_input_type (typeid, input_type, description) VALUES (3, 'roleid', 'subnet_roleid field of ref_subnet_role table');
INSERT INTO ref_nnml_input_type (typeid, input_type, description) VALUES (4, 'vlan', 'vlan number (0 if unknown)');
INSERT INTO ref_nnml_input_type (typeid, input_type, description) VALUES (5, 'ispublic', 'is ip public');
INSERT INTO ref_nnml_input_type (typeid, input_type, description) VALUES (6, 'netnum', 'network number (mask) for ip');
INSERT INTO ref_nnml_input_type (typeid, input_type, description) VALUES (7, 'ip_exists', 'ip exists in table');
INSERT INTO ref_nnml_input_type (typeid, input_type, description) VALUES (8, 'mac_exists', 'mac exists in table');
INSERT INTO ref_nnml_input_type (typeid, input_type, description) VALUES (9, 'ip_info_exists', 'ip exists in src_ip_info table');
INSERT INTO ref_nnml_input_type (typeid, input_type, description) VALUES (10, 'tcp_port', 'opened tcp ports from src_scan_port table');
INSERT INTO ref_nnml_input_type (typeid, input_type, description) VALUES (11, 'udp_port', 'opened udp ports from src_scan_port table');
INSERT INTO ref_nnml_input_type (typeid, input_type, description) VALUES (12, 'icmp', 'icmp from src_scan_port table');
INSERT INTO ref_nnml_input_type (typeid, input_type, description) VALUES (13, 'nmap_script_exists', 'nmap script exists in src_scan_script table');
INSERT INTO ref_nnml_input_type (typeid, input_type, description) VALUES (14, 'nmap_osmatch_exists', 'nmap osmatch exists in src_scan_osmatch table');
INSERT INTO ref_nnml_input_type (typeid, input_type, description) VALUES (15, 'nmap_script_value_exists', 'nmap script value pair exists in src_scan_script table');
INSERT INTO ref_nnml_input_type (typeid, input_type, description) VALUES (16, 'nmap_service_product_exists', 'nmap service product exists in src_scan_service table');
INSERT INTO ref_nnml_input_type (typeid, input_type, description) VALUES (17, 'nmap_service_extrainfo_exists', 'nmap service extrainfo exists in src_scan_service table');
INSERT INTO ref_nnml_input_type (typeid, input_type, description) VALUES (18, 'nmap_service_cpe_exists', 'nmap service cpe exists in src_scan_service table');
INSERT INTO ref_nnml_input_type (typeid, input_type, description) VALUES (19, 'nmap_osclass_type_exists', 'nmap osclass type exists in src_scan_osclass table');
INSERT INTO ref_nnml_input_type (typeid, input_type, description) VALUES (20, 'nmap_osclass_vendor_exists', 'nmap osclass vendor exists in src_scan_osclass table');
INSERT INTO ref_nnml_input_type (typeid, input_type, description) VALUES (21, 'nmap_osclass_osfamily_exists', 'nmap osclass odfamily exists in src_scan_osclass table');
INSERT INTO ref_nnml_input_type (typeid, input_type, description) VALUES (22, 'nmap_osclass_cpe_exists', 'nmap osclass cpe exists in src_scan_osclass table');
INSERT INTO ref_nnml_input_type (typeid, input_type, description) VALUES (23, 'word', 'word exists in parsing');

INSERT INTO ref_nnml_ip_exists_table (id, tablename) VALUES (1, 'src_activaire');
INSERT INTO ref_nnml_ip_exists_table (id, tablename) VALUES (2, 'src_enplug_edu');
INSERT INTO ref_nnml_ip_exists_table (id, tablename) VALUES (3, 'src_arp');
INSERT INTO ref_nnml_ip_exists_table (id, tablename) VALUES (4, 'src_mist');
INSERT INTO ref_nnml_ip_exists_table (id, tablename) VALUES (5, 'src_ruckussz_wap');
INSERT INTO ref_nnml_ip_exists_table (id, tablename) VALUES (6, 'src_snmp_wap');
INSERT INTO ref_nnml_ip_exists_table (id, tablename) VALUES (7, 'src_ruckussz_wlc');
INSERT INTO ref_nnml_ip_exists_table (id, tablename) VALUES (8, 'src_snmp_wlc');
INSERT INTO ref_nnml_ip_exists_table (id, tablename) VALUES (9, 'src_snmp_system');
INSERT INTO ref_nnml_ip_exists_table (id, tablename) VALUES (10, 'src_snmp_sysor');
INSERT INTO ref_nnml_ip_exists_table (id, tablename) VALUES (11, 'src_snmp_router');
INSERT INTO ref_nnml_ip_exists_table (id, tablename) VALUES (12, 'src_snmp_lldp');
INSERT INTO ref_nnml_ip_exists_table (id, tablename) VALUES (13, 'src_snmp_cdp');
INSERT INTO ref_nnml_ip_exists_table (id, tablename) VALUES (14, 'src_if');

INSERT INTO ref_nnml_mac_exists_table (id, tablename) VALUES (1, 'src_activaire');
INSERT INTO ref_nnml_mac_exists_table (id, tablename) VALUES (2, 'src_enplug_edu');
INSERT INTO ref_nnml_mac_exists_table (id, tablename) VALUES (3, 'src_arp');
INSERT INTO ref_nnml_mac_exists_table (id, tablename) VALUES (4, 'src_mist');
INSERT INTO ref_nnml_mac_exists_table (id, tablename) VALUES (5, 'src_ruckussz_wap');
INSERT INTO ref_nnml_mac_exists_table (id, tablename) VALUES (6, 'src_snmp_wap');
INSERT INTO ref_nnml_mac_exists_table (id, tablename) VALUES (7, 'src_mac');

INSERT INTO ref_nnml_word_source(srcid, src_name, query, min_word_num, min_word_percent, max_word_percent) VALUES (1, 'src_scan_script_1', "SELECT tmp_nnml_ip.ipid, src_scan_script.value, src_scan_script.script FROM tmp_nnml_ip INNER JOIN src_scan_ip ON tmp_nnml_ip.ip=src_scan_ip.ip INNER JOIN src_scan_port ON src_scan_ip.ipid=src_scan_port.ipid INNER JOIN src_scan_script ON src_scan_port.portid=src_scan_script.portid WHERE src_scan_script.script IN ('http-comments-displayer');", 3, 2.0, 95.0);
INSERT INTO ref_nnml_word_source(srcid, src_name, query, min_word_num, min_word_percent, max_word_percent) VALUES (2, 'src_scan_script_2', "SELECT tmp_nnml_ip.ipid, src_scan_script.value, src_scan_script.script FROM tmp_nnml_ip INNER JOIN src_scan_ip ON tmp_nnml_ip.ip=src_scan_ip.ip INNER JOIN src_scan_port ON src_scan_ip.ipid=src_scan_port.ipid INNER JOIN src_scan_script ON src_scan_port.portid=src_scan_script.portid WHERE src_scan_script.script IN ('http-server-header', 'http-title', 'ssl-cert', 'ssh-auth-methods', 'ssh-hostkey', 'ssh2-enum-algos', 'ntp-info', 'snmp-info', 'banner', 'dns-service-discovery', 'sip-methods', 'rtsp-url-brute', 'vnc-info', 'ftp-anon', 'ftp-syst', 'rpcinfo', 'snmp-processes', 'afp-serverinfo', 'modbus-discover', 'ldap-rootdse') AND value NOT IN ('Couldn\\\'t find any comments.', 'Couldn\\\'t find any error pages.', CHR(10), 'Site doesn\\\'t have a title (text/html).', '', 'Site doesn\\\'t have a title.');", 3, 0, 95.0);
INSERT INTO ref_nnml_word_source(srcid, src_name, query, min_word_num, min_word_percent, max_word_percent) VALUES (3, 'src_scan_script_3', "SELECT tmp_nnml_ip.ipid, src_scan_script.value, src_scan_script.script FROM tmp_nnml_ip INNER JOIN src_scan_ip ON tmp_nnml_ip.ip=src_scan_ip.ip INNER JOIN src_scan_port ON src_scan_ip.ipid=src_scan_port.ipid INNER JOIN src_scan_script ON src_scan_port.portid=src_scan_script.portid WHERE src_scan_script.script IN ('http-errors', 'http-headers', 'http-security-headers', 'http-methods', 'ssl-enum-ciphers', 'dns-nsid', 'snmp-netstat', 'http-enum', 'http-favicon', 'mdns-service-discovery') AND value NOT IN ('Couldn\\\'t find any comments.', 'Couldn\\\'t find any error pages.', CHR(10), 'Site doesn\\\'t have a title (text/html).', '', 'Site doesn\\\'t have a title.');", 3, 0.5, 95.0);
INSERT INTO ref_nnml_word_source(srcid, src_name, query, min_word_num, min_word_percent, max_word_percent) VALUES (10, 'src_ip_info', 'SELECT tmp_nnml_ip.ipid, src_ip_info.value, ref_scan_ip_info.info FROM tmp_nnml_ip INNER JOIN src_ip ON tmp_nnml_ip.ip=src_ip.ip INNER JOIN src_ip_info ON src_ip.ipid=src_ip_info.ipid INNER JOIN ref_scan_ip_info ON src_ip_info.infoid=ref_scan_ip_info.infoid WHERE ref_scan_ip_info.info IN (\'name\', \'hostname\', \'description\');', 3, 0.5, 95.0);
INSERT INTO ref_nnml_word_source(srcid, src_name, query, min_word_num, min_word_percent, max_word_percent) VALUES (11, 'src_activaire', 'SELECT tmp_nnml_ip.ipid, src_activaire.make_model, \'\' FROM tmp_nnml_ip INNER JOIN src_activaire ON tmp_nnml_ip.ip=src_activaire.ip;', 3, 0, 95.0);
INSERT INTO ref_nnml_word_source(srcid, src_name, query, min_word_num, min_word_percent, max_word_percent) VALUES (12, 'src_if_ifdescr', 'SELECT tmp_nnml_ip.ipid, src_if.ifdescr, \'\' FROM tmp_nnml_ip INNER JOIN src_if ON tmp_nnml_ip.ip=src_if.device WHERE src_if.ifdescr IS NOT NULL;', 3, 0.5, 95.0);
INSERT INTO ref_nnml_word_source(srcid, src_name, query, min_word_num, min_word_percent, max_word_percent) VALUES (13, 'src_if_ifname', 'SELECT tmp_nnml_ip.ipid, src_if.ifname, \'\' FROM tmp_nnml_ip INNER JOIN src_if ON tmp_nnml_ip.ip=src_if.device WHERE src_if.ifname IS NOT NULL;', 3, 0.5, 95.0);
INSERT INTO ref_nnml_word_source(srcid, src_name, query, min_word_num, min_word_percent, max_word_percent) VALUES (14, 'src_if_ifalias', 'SELECT tmp_nnml_ip.ipid, src_if.ifalias, \'\' FROM tmp_nnml_ip INNER JOIN src_if ON tmp_nnml_ip.ip=src_if.device WHERE src_if.ifalias IS NOT NULL;', 3, 0.5, 95.0);
INSERT INTO ref_nnml_word_source(srcid, src_name, query, min_word_num, min_word_percent, max_word_percent) VALUES (15, 'src_mist', 'SELECT tmp_nnml_ip.ipid, src_mist.model, \'\' FROM tmp_nnml_ip INNER JOIN src_mist ON tmp_nnml_ip.ip=src_mist.ip;', 3, 0, 95.0);
INSERT INTO ref_nnml_word_source(srcid, src_name, query, min_word_num, min_word_percent, max_word_percent) VALUES (16, 'src_ruckussz_wap', 'SELECT tmp_nnml_ip.ipid, src_ruckussz_wap.model, \'\' FROM tmp_nnml_ip INNER JOIN src_ruckussz_wap ON tmp_nnml_ip.ip=src_ruckussz_wap.ip;', 3, 0, 95.0);
INSERT INTO ref_nnml_word_source(srcid, src_name, query, min_word_num, min_word_percent, max_word_percent) VALUES (17, 'src_scan_osclass_type', 'SELECT tmp_nnml_ip.ipid, src_scan_osclass.type, \'\' FROM tmp_nnml_ip INNER JOIN src_scan_ip ON tmp_nnml_ip.ip=src_scan_ip.ip INNER JOIN src_scan_osmatch ON src_scan_ip.ipid=src_scan_osmatch.ipid INNER JOIN src_scan_osclass ON src_scan_osmatch.osmatchid=src_scan_osclass.osmatchid;', 3, 0, 95.0);
INSERT INTO ref_nnml_word_source(srcid, src_name, query, min_word_num, min_word_percent, max_word_percent) VALUES (18, 'src_scan_osclass_vendor', 'SELECT tmp_nnml_ip.ipid, src_scan_osclass.vendor, \'\' FROM tmp_nnml_ip INNER JOIN src_scan_ip ON tmp_nnml_ip.ip=src_scan_ip.ip INNER JOIN src_scan_osmatch ON src_scan_ip.ipid=src_scan_osmatch.ipid INNER JOIN src_scan_osclass ON src_scan_osmatch.osmatchid=src_scan_osclass.osmatchid;', 3, 0, 95.0);
INSERT INTO ref_nnml_word_source(srcid, src_name, query, min_word_num, min_word_percent, max_word_percent) VALUES (19, 'src_scan_osclass_osfamily', 'SELECT tmp_nnml_ip.ipid, src_scan_osclass.osfamily, \'\' FROM tmp_nnml_ip INNER JOIN src_scan_ip ON tmp_nnml_ip.ip=src_scan_ip.ip INNER JOIN src_scan_osmatch ON src_scan_ip.ipid=src_scan_osmatch.ipid INNER JOIN src_scan_osclass ON src_scan_osmatch.osmatchid=src_scan_osclass.osmatchid;', 3, 0, 95.0);
INSERT INTO ref_nnml_word_source(srcid, src_name, query, min_word_num, min_word_percent, max_word_percent) VALUES (20, 'src_scan_osclass_cpe', 'SELECT tmp_nnml_ip.ipid, src_scan_osclass.cpe, \'\' FROM tmp_nnml_ip INNER JOIN src_scan_ip ON tmp_nnml_ip.ip=src_scan_ip.ip INNER JOIN src_scan_osmatch ON src_scan_ip.ipid=src_scan_osmatch.ipid INNER JOIN src_scan_osclass ON src_scan_osmatch.osmatchid=src_scan_osclass.osmatchid;', 3, 0.5, 95.0);
INSERT INTO ref_nnml_word_source(srcid, src_name, query, min_word_num, min_word_percent, max_word_percent) VALUES (21, 'src_scan_osmatch', 'SELECT tmp_nnml_ip.ipid, src_scan_osmatch.name, \'\' FROM tmp_nnml_ip INNER JOIN src_scan_ip ON tmp_nnml_ip.ip=src_scan_ip.ip INNER JOIN src_scan_osmatch ON src_scan_ip.ipid=src_scan_osmatch.ipid;', 3, 0.5, 95.0);
INSERT INTO ref_nnml_word_source(srcid, src_name, query, min_word_num, min_word_percent, max_word_percent) VALUES (22, 'src_scan_service_product', 'SELECT tmp_nnml_ip.ipid, src_scan_service.product, \'\' FROM tmp_nnml_ip INNER JOIN src_scan_ip ON tmp_nnml_ip.ip=src_scan_ip.ip INNER JOIN src_scan_port ON src_scan_ip.ipid=src_scan_port.ipid INNER JOIN src_scan_service ON src_scan_port.portid=src_scan_service.portid;', 3, 0, 95.0);
INSERT INTO ref_nnml_word_source(srcid, src_name, query, min_word_num, min_word_percent, max_word_percent) VALUES (23, 'src_scan_service_extrainfo', 'SELECT tmp_nnml_ip.ipid, src_scan_service.extrainfo, \'\' FROM tmp_nnml_ip INNER JOIN src_scan_ip ON tmp_nnml_ip.ip=src_scan_ip.ip INNER JOIN src_scan_port ON src_scan_ip.ipid=src_scan_port.ipid INNER JOIN src_scan_service ON src_scan_port.portid=src_scan_service.portid WHERE src_scan_service.extrainfo IS NOT NULL AND src_scan_service.extrainfo NOT LIKE \'Domain:%\' AND src_scan_service.extrainfo NOT LIKE \'MAC %\' AND src_scan_service.extrainfo NOT LIKE \'name:%\' AND src_scan_service.extrainfo NOT LIKE \'server time:%\' AND src_scan_service.extrainfo NOT LIKE \'workgroup:%\';', 3, 0, 95.0);
INSERT INTO ref_nnml_word_source(srcid, src_name, query, min_word_num, min_word_percent, max_word_percent) VALUES (24, 'src_scan_service_cpe', 'SELECT tmp_nnml_ip.ipid, src_scan_service.cpe, \'\' FROM tmp_nnml_ip INNER JOIN src_scan_ip ON tmp_nnml_ip.ip=src_scan_ip.ip INNER JOIN src_scan_port ON src_scan_ip.ipid=src_scan_port.ipid INNER JOIN src_scan_service ON src_scan_port.portid=src_scan_service.portid WHERE src_scan_service.cpe IS NOT NULL;', 3, 0, 95.0);
INSERT INTO ref_nnml_word_source(srcid, src_name, query, min_word_num, min_word_percent, max_word_percent) VALUES (25, 'src_snmp_sysor', 'SELECT tmp_nnml_ip.ipid, src_snmp_sysor.sysordescr, \'\' FROM tmp_nnml_ip INNER JOIN src_scan_ip ON tmp_nnml_ip.ip=src_scan_ip.ip INNER JOIN src_snmp_sysor ON src_scan_ip.ipid=src_snmp_sysor.ipid;', 3, 0.5, 95.0);
INSERT INTO ref_nnml_word_source(srcid, src_name, query, min_word_num, min_word_percent, max_word_percent) VALUES (26, 'src_snmp_system', 'SELECT tmp_nnml_ip.ipid, src_snmp_system.sysdescr, \'\' FROM tmp_nnml_ip INNER JOIN src_scan_ip ON tmp_nnml_ip.ip=src_scan_ip.ip INNER JOIN src_snmp_system ON src_scan_ip.ipid=src_snmp_system.ipid;', 3, 0.5, 95.0);
