CREATE TABLE IF NOT EXISTS shot_host_option ( 
  id BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT, 
  optionid INT UNSIGNED NOT NULL, 
  hostuuid VARCHAR(256) NOT NULL, 
  idtype INT UNSIGNED NOT NULL, 
  ip VARCHAR(39) DEFAULT NULL, 
  mac VARCHAR(12) DEFAULT NULL, 
  name varchar(256) DEFAULT NULL,
  hostname varchar(100) DEFAULT NULL,
  manufacturerid INT UNSIGNED DEFAULT NULL,
  devicetypeid INT UNSIGNED NOT NULL, 
  weight FLOAT NOT NULL, 
  controllerid BIGINT DEFAULT NULL, 
  idoncontroller VARCHAR(256) DEFAULT NULL, 
  ipprefixid INT UNSIGNED DEFAULT NULL, 
  vlan INT UNSIGNED NOT NULL DEFAULT 0, 
  roleid INT UNSIGNED DEFAULT NULL, 
  ispublic BOOLEAN DEFAULT NULL, 
  macvendorid VARCHAR(12) DEFAULT NULL, 
  UNIQUE KEY hostoptiontype (hostuuid, optionid, idtype), 
  KEY hosttype (hostuuid, idtype), 
  KEY optionid (optionid), 
  KEY hostuuid (hostuuid), 
  KEY idtype (idtype), 
  KEY ip (ip), 
  KEY mac (mac), 
  KEY name (name), 
  KEY manufacturerid (manufacturerid), 
  KEY devicetypeid (devicetypeid), 
  KEY weight (weight), 
  KEY controllerid (controllerid), 
  KEY ipprefixid (ipprefixid), 
  KEY roleid (roleid), 
  KEY macvendorid (macvendorid), 
  CONSTRAINT roleid_sho FOREIGN KEY (roleid) REFERENCES ref_subnet_role (subnet_roleid) ON DELETE SET NULL ON UPDATE CASCADE, 
  CONSTRAINT macvendorid_sho FOREIGN KEY (macvendorid) REFERENCES info_mac (assignment) ON DELETE SET NULL ON UPDATE CASCADE, 
  CONSTRAINT manufacturerid_sho FOREIGN KEY (manufacturerid) REFERENCES ref_manufacturer (manufacturerid) ON DELETE SET NULL ON UPDATE CASCADE, 
  CONSTRAINT devicetypeid_sho FOREIGN KEY (devicetypeid) REFERENCES ref_devicetype (devicetypeid) ON DELETE CASCADE ON UPDATE CASCADE, 
  CONSTRAINT ipprefixid_sho FOREIGN KEY (ipprefixid) REFERENCES ref_ipprefix (ipprefixid) ON DELETE SET NULL ON UPDATE CASCADE, 
  CONSTRAINT optionid_sho FOREIGN KEY (optionid) REFERENCES ref_host_option (optionid) ON DELETE CASCADE ON UPDATE CASCADE, 
  CONSTRAINT controllerid_sho FOREIGN KEY (controllerid) REFERENCES shot_host_option (id) ON DELETE SET NULL ON UPDATE CASCADE, 
  CONSTRAINT idtype_sho FOREIGN KEY (idtype) REFERENCES ref_host_idtype (id) ON DELETE CASCADE ON UPDATE CASCADE 
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS shot_host_option_uuid ( 
  id BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT, 
  hostid BIGINT NOT NULL, 
  optionid INT UNSIGNED NOT NULL, 
  uuid_type INT UNSIGNED NOT NULL, 
  uuid VARCHAR(256) NOT NULL, 
  UNIQUE KEY optionuuidtype (optionid, uuid_type, uuid), 
  KEY uuidtype (uuid_type, uuid), 
  KEY optionid (optionid), 
  KEY uuid_type (uuid_type), 
  KEY hostid (hostid), 
  KEY uuid (uuid), 
  CONSTRAINT optionid_shou FOREIGN KEY (optionid) REFERENCES ref_host_option (optionid) ON DELETE CASCADE ON UPDATE CASCADE, 
  CONSTRAINT hostid_shou FOREIGN KEY (hostid) REFERENCES shot_host_option (id) ON DELETE CASCADE ON UPDATE CASCADE, 
  CONSTRAINT uuid_type_shou FOREIGN KEY (uuid_type) REFERENCES ref_host_uuid (id) ON DELETE CASCADE ON UPDATE CASCADE 
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS shot_host_option_link ( 
  id BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT, 
  hostid BIGINT NOT NULL, 
  optionid INT UNSIGNED NOT NULL, 
  linkid INT UNSIGNED NOT NULL, 
  uuid VARCHAR(256) NOT NULL, 
  UNIQUE KEY optionhostlink (optionid, hostid, linkid), 
  KEY hostlink (hostid, linkid);
  KEY linkid (linkid), 
  KEY optionid (optionid), 
  KEY hostid (hostid), 
  KEY uuid (uuid), 
  CONSTRAINT optionid_shol FOREIGN KEY (optionid) REFERENCES ref_host_option (optionid) ON DELETE CASCADE ON UPDATE CASCADE, 
  CONSTRAINT hostid_shol FOREIGN KEY (hostid) REFERENCES shot_host_option (id) ON DELETE CASCADE ON UPDATE CASCADE, 
  CONSTRAINT linkid_shol FOREIGN KEY (linkid) REFERENCES ref_host_link (linkid) ON DELETE CASCADE ON UPDATE CASCADE 
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS shot_host ( 
  hostid BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT, 
  hostuuid VARCHAR(256) NOT NULL, 
  idtype INT UNSIGNED NOT NULL, 
  ip VARCHAR(39) DEFAULT NULL, 
  mac VARCHAR(12) DEFAULT NULL, 
  name varchar(256) DEFAULT NULL,
  hostname varchar(100) DEFAULT NULL,
  manufacturerid INT UNSIGNED DEFAULT NULL,
  devicetypeid INT UNSIGNED NOT NULL, 
  controllerid BIGINT DEFAULT NULL, 
  idoncontroller VARCHAR(256) DEFAULT NULL, 
  ipprefixid INT UNSIGNED DEFAULT NULL, 
  vlan INT UNSIGNED NOT NULL DEFAULT 0, 
  roleid INT UNSIGNED DEFAULT NULL, 
  ispublic BOOLEAN DEFAULT NULL, 
  macvendorid VARCHAR(12) DEFAULT NULL, 
  UNIQUE KEY hosttype (hostuuid, idtype), 
  KEY hostuuid (hostuuid), 
  KEY idtype (idtype), 
  KEY ip (ip), 
  KEY mac (mac), 
  KEY name (name), 
  KEY manufacturerid (manufacturerid), 
  KEY devicetypeid (devicetypeid), 
  KEY controllerid (controllerid), 
  KEY ipprefixid (ipprefixid), 
  KEY roleid (roleid), 
  KEY macvendorid (macvendorid), 
  CONSTRAINT roleid_sh FOREIGN KEY (roleid) REFERENCES ref_subnet_role (subnet_roleid) ON DELETE SET NULL ON UPDATE CASCADE, 
  CONSTRAINT macvendorid_sh FOREIGN KEY (macvendorid) REFERENCES info_mac (assignment) ON DELETE SET NULL ON UPDATE CASCADE, 
  CONSTRAINT manufacturerid_sh FOREIGN KEY (manufacturerid) REFERENCES ref_manufacturer (manufacturerid) ON DELETE SET NULL ON UPDATE CASCADE, 
  CONSTRAINT devicetypeid_sh FOREIGN KEY (devicetypeid) REFERENCES ref_devicetype (devicetypeid) ON DELETE CASCADE ON UPDATE CASCADE, 
  CONSTRAINT ipprefixid_sh FOREIGN KEY (ipprefixid) REFERENCES ref_ipprefix (ipprefixid) ON DELETE SET NULL ON UPDATE CASCADE, 
  CONSTRAINT controllerid_sh FOREIGN KEY (controllerid) REFERENCES shot_host (hostid) ON DELETE SET NULL ON UPDATE CASCADE, 
  CONSTRAINT idtype_sh FOREIGN KEY (idtype) REFERENCES ref_host_idtype (id) ON DELETE CASCADE ON UPDATE CASCADE 
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS shot_host_uuid ( 
  id BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT, 
  hostid BIGINT NOT NULL, 
  uuid_type INT UNSIGNED NOT NULL, 
  uuid VARCHAR(256) NOT NULL, 
  UNIQUE KEY uuidtype (uuid_type, uuid), 
  KEY uuid_type (uuid_type), 
  KEY hostid (hostid), 
  KEY uuid (uuid), 
  CONSTRAINT hostid_shu FOREIGN KEY (hostid) REFERENCES shot_host (hostid) ON DELETE CASCADE ON UPDATE CASCADE, 
  CONSTRAINT uuid_type_shu FOREIGN KEY (uuid_type) REFERENCES ref_host_uuid (id) ON DELETE CASCADE ON UPDATE CASCADE 
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS shot_host_link ( 
  id BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT, 
  hostid BIGINT NOT NULL, 
  linkid INT UNSIGNED NOT NULL, 
  uuid VARCHAR(256) NOT NULL, 
  UNIQUE KEY hostlink (hostid, linkid), 
  KEY linkid (linkid), 
  KEY hostid (hostid), 
  KEY uuid (uuid), 
  CONSTRAINT hostid_shl FOREIGN KEY (hostid) REFERENCES shot_host (hostid) ON DELETE CASCADE ON UPDATE CASCADE, 
  CONSTRAINT linkid_shl FOREIGN KEY (linkid) REFERENCES ref_host_link (linkid) ON DELETE CASCADE ON UPDATE CASCADE 
) ENGINE=InnoDB;


