INSERT INTO ref_region (regionid, netboxid, region, region_alias, description, parentid) VALUES (0, NULL, '', '', NULL, NULL);

INSERT INTO ref_site (siteid, netboxid, site, site_alias, description, active, regionid, groupid, tenantid, facility, time_zone, physical_address, shipping_address, latitude, longitude, contact_name, contact_phone, contact_email, importance, comments) VALUES (0, NULL, '', '', NULL, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL);

INSERT INTO ref_manufacturer manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (0, NULL, '', '', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (1000, NULL, 'Undefined', 'undefined', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (1, NULL, 'Activaire', 'activaire', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (2, NULL, 'Advidia', 'advidia', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (3, NULL, 'APC', 'apc', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (4, NULL, 'Apple', 'apple', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (5, NULL, 'Arcules', 'arcules', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (6, NULL, 'Arista', 'arista', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (7, NULL, 'Ashly', 'ashly', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (8, NULL, 'Audinate', 'audinate', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (9, NULL, 'Avaya', 'avaya', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (10, NULL, 'Axis', 'axis', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (11, NULL, 'Biamp', 'biamp', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (12, NULL, 'Bosch', 'bosch', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (13, NULL, 'Brocade', 'brocade', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (14, NULL, 'Brother', 'brother', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (15, NULL, 'BSS', 'bss', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (16, NULL, 'Canon', 'canon', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (17, NULL, 'Cisco', 'cisco', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (18, NULL, 'Crestron', 'crestron', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (19, NULL, 'Dell', 'dell', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (20, NULL, 'Digium', 'digium', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (21, NULL, 'DMX', 'dmx', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (22, NULL, 'Eaton', 'eaton', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (23, NULL, 'Enplug', 'enplug', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (24, NULL, 'Epson', 'epson', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (25, NULL, 'Fortinet', 'fortinet', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (26, NULL, 'Furman', 'furman', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (27, NULL, 'Geist', 'geist', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (28, NULL, 'Gigaset', 'gigaset', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (29, NULL, 'Grandstream', 'grandstream', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (30, NULL, 'Hikvision', 'hikvision', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (31, NULL, 'Hitachi', 'hitachi', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (32, NULL, 'Honeywell', 'honeywell', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (33, NULL, 'HP', 'hp', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (34, NULL, 'Intel', 'intel', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (35, NULL, 'Juniper', 'juniper', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (36, NULL, 'Konfitel', 'konfitel', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (37, NULL, 'Legrand', 'legrand', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (38, NULL, 'Lenovo', 'lenovo', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (39, NULL, 'LG', 'lg', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (40, NULL, 'LifeSafety', 'lifesafety', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (41, NULL, 'Mercury Security', 'mercury-security', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (42, NULL, 'Mersive', 'mersive', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (43, NULL, 'Microsoft', 'microsoft', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (44, NULL, 'Mikrotik', 'mikrotik', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (45, NULL, 'Minix', 'minix', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (46, NULL, 'Mitsubishi', 'mitsubishi', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (47, NULL, 'NEC', 'nec', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (48, NULL, 'Netgear', 'netgear', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (49, NULL, 'Opengear', 'opengear', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (50, NULL, 'Palo Alto', 'palo-alto', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (51, NULL, 'Panasonic', 'panasonic', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (52, NULL, 'Panduit', 'panduit', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (53, NULL, 'Polycom', 'polycom', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (54, NULL, 'QNAP', 'qnap', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (55, NULL, 'QSC', 'qsc', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (56, NULL, 'Raspberry Pi', 'raspberry-pi', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (57, NULL, 'Riello', 'riello', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (58, NULL, 'Ruckus', 'ruckus', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (59, NULL, 'S2 Security', 's2-security', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (60, NULL, 'Sennheiser', 'sennheiser', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (61, NULL, 'Shure', 'shure', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (62, NULL, 'Siemens', 'siemens', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (63, NULL, 'Snom', 'snom', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (64, NULL, 'Sonos', 'sonos', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (65, NULL, 'Sony', 'sony', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (66, NULL, 'Super Micro', 'super-micro', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (67, NULL, 'Tesira', 'tesira', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (68, NULL, 'Ubiquiti', 'ubiquiti', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (69, NULL, 'VMWare', 'vmware', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (70, NULL, 'Wiibrain', 'wiibrain', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (71, NULL, 'Xerox', 'xerox', NULL);
INSERT INTO ref_manufacturer (manufacturerid, netboxid, manufacturer, manufacturer_alias, description) VALUES (72, NULL, 'Yealink', 'yealink', NULL);

INSERT INTO ref_devicerole (deviceroleid, netboxid, devicerole, devicerole_alias, description, vm_role) VALUES (0, NULL, '', '', NULL, NULL);
INSERT INTO ref_devicerole (deviceroleid, netboxid, devicerole, devicerole_alias, description, vm_role) VALUES (1000, NULL, 'Undefined', 'undefined', NULL, NULL);
INSERT INTO ref_devicerole (deviceroleid, netboxid, devicerole, devicerole_alias, description, vm_role) VALUES (1, NULL, 'Access Blade', 'access-blade', NULL, NULL);
INSERT INTO ref_devicerole (deviceroleid, netboxid, devicerole, devicerole_alias, description, vm_role) VALUES (2, NULL, 'Access Chassis', 'access-chassis', NULL, NULL);
INSERT INTO ref_devicerole (deviceroleid, netboxid, devicerole, devicerole_alias, description, vm_role) VALUES (3, NULL, 'Access Control', 'access-control', NULL, NULL);
INSERT INTO ref_devicerole (deviceroleid, netboxid, devicerole, devicerole_alias, description, vm_role) VALUES (4, NULL, 'Access Switch', 'access-switch', NULL, NULL);
INSERT INTO ref_devicerole (deviceroleid, netboxid, devicerole, devicerole_alias, description, vm_role) VALUES (5, NULL, 'Amplifier', 'amplifier', NULL, NULL);
INSERT INTO ref_devicerole (deviceroleid, netboxid, devicerole, devicerole_alias, description, vm_role) VALUES (6, NULL, 'Backbone Router', 'backbone-router', NULL, NULL);
INSERT INTO ref_devicerole (deviceroleid, netboxid, devicerole, devicerole_alias, description, vm_role) VALUES (7, NULL, 'BGM Player', 'bgm-player', NULL, NULL);
INSERT INTO ref_devicerole (deviceroleid, netboxid, devicerole, devicerole_alias, description, vm_role) VALUES (8, NULL, 'Border Router', 'border-router', NULL, NULL);
INSERT INTO ref_devicerole (deviceroleid, netboxid, devicerole, devicerole_alias, description, vm_role) VALUES (9, NULL, 'Building Management', 'building-management', NULL, NULL);
INSERT INTO ref_devicerole (deviceroleid, netboxid, devicerole, devicerole_alias, description, vm_role) VALUES (10, NULL, 'Camera', 'camera', NULL, NULL);
INSERT INTO ref_devicerole (deviceroleid, netboxid, devicerole, devicerole_alias, description, vm_role) VALUES (11, NULL, 'Channel Expander', 'channel-expander', NULL, NULL);
INSERT INTO ref_devicerole (deviceroleid, netboxid, devicerole, devicerole_alias, description, vm_role) VALUES (12, NULL, 'Codec', 'codec', NULL, NULL);
INSERT INTO ref_devicerole (deviceroleid, netboxid, devicerole, devicerole_alias, description, vm_role) VALUES (13, NULL, 'Computer', 'computer', NULL, NULL);
INSERT INTO ref_devicerole (deviceroleid, netboxid, devicerole, devicerole_alias, description, vm_role) VALUES (14, NULL, 'Conference Phone', 'conference-phone', NULL, NULL);
INSERT INTO ref_devicerole (deviceroleid, netboxid, devicerole, devicerole_alias, description, vm_role) VALUES (15, NULL, 'Console Server', 'console-server', NULL, NULL);
INSERT INTO ref_devicerole (deviceroleid, netboxid, devicerole, devicerole_alias, description, vm_role) VALUES (16, NULL, 'Control Panel', 'control-panel', NULL, NULL);
INSERT INTO ref_devicerole (deviceroleid, netboxid, devicerole, devicerole_alias, description, vm_role) VALUES (17, NULL, 'Core Switch', 'core-switch', NULL, NULL);
INSERT INTO ref_devicerole (deviceroleid, netboxid, devicerole, devicerole_alias, description, vm_role) VALUES (18, NULL, 'Digital Signage', 'digital-signage', NULL, NULL);
INSERT INTO ref_devicerole (deviceroleid, netboxid, devicerole, devicerole_alias, description, vm_role) VALUES (19, NULL, 'Distribution Switch', 'distribution-switch', NULL, NULL);
INSERT INTO ref_devicerole (deviceroleid, netboxid, devicerole, devicerole_alias, description, vm_role) VALUES (20, NULL, 'DSP', 'dsp', NULL, NULL);
INSERT INTO ref_devicerole (deviceroleid, netboxid, devicerole, devicerole_alias, description, vm_role) VALUES (21, NULL, 'Environmental monitor', 'environmental-monitor', NULL, NULL);
INSERT INTO ref_devicerole (deviceroleid, netboxid, devicerole, devicerole_alias, description, vm_role) VALUES (22, NULL, 'Firewall', 'firewall', NULL, NULL);
INSERT INTO ref_devicerole (deviceroleid, netboxid, devicerole, devicerole_alias, description, vm_role) VALUES (23, NULL, 'Gateway', 'gateway', NULL, NULL);
INSERT INTO ref_devicerole (deviceroleid, netboxid, devicerole, devicerole_alias, description, vm_role) VALUES (24, NULL, 'Hypervisor', 'hypervisor', NULL, NULL);
INSERT INTO ref_devicerole (deviceroleid, netboxid, devicerole, devicerole_alias, description, vm_role) VALUES (25, NULL, 'ISP Switch', 'isp-switch', NULL, NULL);
INSERT INTO ref_devicerole (deviceroleid, netboxid, devicerole, devicerole_alias, description, vm_role) VALUES (26, NULL, 'Microphone', 'microphone', NULL, NULL);
INSERT INTO ref_devicerole (deviceroleid, netboxid, devicerole, devicerole_alias, description, vm_role) VALUES (27, NULL, 'NAS', 'nas', NULL, NULL);
INSERT INTO ref_devicerole (deviceroleid, netboxid, devicerole, devicerole_alias, description, vm_role) VALUES (28, NULL, 'Patch Panel', 'patch-panel', NULL, NULL);
INSERT INTO ref_devicerole (deviceroleid, netboxid, devicerole, devicerole_alias, description, vm_role) VALUES (29, NULL, 'PDU', 'pdu', NULL, NULL);
INSERT INTO ref_devicerole (deviceroleid, netboxid, devicerole, devicerole_alias, description, vm_role) VALUES (30, NULL, 'Phone', 'phone', NULL, NULL);
INSERT INTO ref_devicerole (deviceroleid, netboxid, devicerole, devicerole_alias, description, vm_role) VALUES (31, NULL, 'Print Server', 'print server', NULL, NULL);
INSERT INTO ref_devicerole (deviceroleid, netboxid, devicerole, devicerole_alias, description, vm_role) VALUES (32, NULL, 'Printer', 'printer', NULL, NULL);
INSERT INTO ref_devicerole (deviceroleid, netboxid, devicerole, devicerole_alias, description, vm_role) VALUES (33, NULL, 'Projector', 'projector', NULL, NULL);
INSERT INTO ref_devicerole (deviceroleid, netboxid, devicerole, devicerole_alias, description, vm_role) VALUES (34, NULL, 'Remote Access Controller', 'remote-access-controller', NULL, NULL);
INSERT INTO ref_devicerole (deviceroleid, netboxid, devicerole, devicerole_alias, description, vm_role) VALUES (35, NULL, 'Room Controller', 'room-controller', NULL, NULL);
INSERT INTO ref_devicerole (deviceroleid, netboxid, devicerole, devicerole_alias, description, vm_role) VALUES (36, NULL, 'Router', 'router', NULL, NULL);
INSERT INTO ref_devicerole (deviceroleid, netboxid, devicerole, devicerole_alias, description, vm_role) VALUES (37, NULL, 'Screen Share', 'screen-share', NULL, NULL);
INSERT INTO ref_devicerole (deviceroleid, netboxid, devicerole, devicerole_alias, description, vm_role) VALUES (38, NULL, 'Server', 'server', NULL, NULL);
INSERT INTO ref_devicerole (deviceroleid, netboxid, devicerole, devicerole_alias, description, vm_role) VALUES (39, NULL, 'Server Blade', 'server-blade', NULL, NULL);
INSERT INTO ref_devicerole (deviceroleid, netboxid, devicerole, devicerole_alias, description, vm_role) VALUES (40, NULL, 'Server Blade Chassis', 'server-blade-chassis', NULL, NULL);
INSERT INTO ref_devicerole (deviceroleid, netboxid, devicerole, devicerole_alias, description, vm_role) VALUES (41, NULL, 'Supervisor', 'supervisor', NULL, NULL);
INSERT INTO ref_devicerole (deviceroleid, netboxid, devicerole, devicerole_alias, description, vm_role) VALUES (42, NULL, 'Switch', 'switch', NULL, NULL);
INSERT INTO ref_devicerole (deviceroleid, netboxid, devicerole, devicerole_alias, description, vm_role) VALUES (43, NULL, 'UPS', 'ups', NULL, NULL);
INSERT INTO ref_devicerole (deviceroleid, netboxid, devicerole, devicerole_alias, description, vm_role) VALUES (44, NULL, 'Video Switcher', 'video-switcher', NULL, NULL);
INSERT INTO ref_devicerole (deviceroleid, netboxid, devicerole, devicerole_alias, description, vm_role) VALUES (45, NULL, 'VMS', 'vms', NULL, NULL);
INSERT INTO ref_devicerole (deviceroleid, netboxid, devicerole, devicerole_alias, description, vm_role) VALUES (46, NULL, 'WAP', 'wap', NULL, NULL);
INSERT INTO ref_devicerole (deviceroleid, netboxid, devicerole, devicerole_alias, description, vm_role) VALUES (47, NULL, 'WLC', 'wlc', NULL, NULL);

INSERT INTO ref_platform (platformid, netboxid, platform, platform_alias, description, manufacturerid) VALUES (0, NULL, '', '', NULL, 0);
INSERT INTO ref_platform (platformid, netboxid, platform, platform_alias, description, manufacturerid) VALUES (1000, NULL, 'Undefined', 'undefined', NULL, 0);
INSERT INTO ref_platform (platformid, netboxid, platform, platform_alias, description, manufacturerid) SELECT 1, NULL, 'Arista EOS', 'arista-eos', NULL, manufacturerid FROM ref_manufacturer WHERE manufacturer_alias='arista';
INSERT INTO ref_platform (platformid, netboxid, platform, platform_alias, description, manufacturerid) SELECT 2, NULL, 'Brocade OS', 'brocade-os', NULL, manufacturerid FROM ref_manufacturer WHERE manufacturer_alias='brocade';
INSERT INTO ref_platform (platformid, netboxid, platform, platform_alias, description, manufacturerid) SELECT 3, NULL, 'Cisco IOS', 'cisco-ios', NULL, manufacturerid FROM ref_manufacturer WHERE manufacturer_alias='cisco';
INSERT INTO ref_platform (platformid, netboxid, platform, platform_alias, description, manufacturerid) SELECT 4, NULL, 'Cisco NX-OS', 'cisco-nx-os', NULL, manufacturerid FROM ref_manufacturer WHERE manufacturer_alias='cisco';
INSERT INTO ref_platform (platformid, netboxid, platform, platform_alias, description, manufacturerid) SELECT 5, NULL, 'ESXi Hypervisor', 'esxi-hypervisor', NULL, manufacturerid FROM ref_manufacturer WHERE manufacturer_alias='vmware';
INSERT INTO ref_platform (platformid, netboxid, platform, platform_alias, description, manufacturerid) SELECT 6, NULL, 'FortiOS', 'fortios', NULL, manufacturerid FROM ref_manufacturer WHERE manufacturer_alias='fortinet';
INSERT INTO ref_platform (platformid, netboxid, platform, platform_alias, description, manufacturerid) SELECT 7, NULL, 'Juniper Junos', 'juniper-junos', NULL,  manufacturerid FROM ref_manufacturer WHERE manufacturer_alias='juniper';
INSERT INTO ref_platform (platformid, netboxid, platform, platform_alias, description, manufacturerid) VALUES (8, NULL, 'Linux', 'linux', NULL, NULL);
INSERT INTO ref_platform (platformid, netboxid, platform, platform_alias, description, manufacturerid) SELECT 9, NULL, 'Windows', 'windows', NULL,  manufacturerid FROM ref_manufacturer WHERE manufacturer_alias='microsoft';

INSERT INTO ref_subdevice_role (subdevice_roleid, subdevice_role, subdevice_role_alias) VALUES (0, '', '');
INSERT INTO ref_subdevice_role (subdevice_roleid, subdevice_role, subdevice_role_alias) VALUES (1, 'Parent', 'parent');
INSERT INTO ref_subdevice_role (subdevice_roleid, subdevice_role, subdevice_role_alias) VALUES (2, 'Child', 'child');

INSERT INTO ref_devicetype (devicetypeid, netboxid, model, model_alias, manufacturerid, subdevice_roleid, part_number, u_height, is_full_depth, airflow, comments, parentid) VALUES (0, NULL, '', '', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO ref_devicetype (devicetypeid, netboxid, model, model_alias, manufacturerid, subdevice_roleid, part_number, u_height, is_full_depth, airflow, comments, parentid) VALUES (1000, NULL, 'Undefined', 'undefined', 1000, NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO ref_ipfamily (familyid, family) VALUES (1, 'IPv4');
INSERT INTO ref_ipfamily (familyid, family) VALUES (2, 'IPv6');

INSERT INTO ref_ipaddress_role (ipaddress_roleid, ipaddress_role) VALUES (1, 'Loopback');
INSERT INTO ref_ipaddress_role (ipaddress_roleid, ipaddress_role) VALUES (2, 'Secondary');

INSERT INTO ref_ipaddress_source (sourceid, description, tablename) VALUES (1, 'IP prefix from ref', 'ref_ipprefix');
INSERT INTO ref_ipaddress_source (sourceid, description, tablename) VALUES (2, 'IP range from ref', 'ref_iprange');
INSERT INTO ref_ipaddress_source (sourceid, description, tablename) VALUES (3, 'IP address from ref', 'ref_ipaddress');
INSERT INTO ref_ipaddress_source (sourceid, description, tablename) VALUES (4, 'Static IP address from ref', 'ref_static_device');

INSERT INTO ref_scan_ip_info (infoid, info) VALUES (1, 'snmp_community');
INSERT INTO ref_scan_ip_info (infoid, info) VALUES (2, 'ssh_username');
INSERT INTO ref_scan_ip_info (infoid, info) VALUES (3, 'ssh_password');
INSERT INTO ref_scan_ip_info (infoid, info) VALUES (4, 'telnet_username');
INSERT INTO ref_scan_ip_info (infoid, info) VALUES (5, 'telnet_password');

INSERT INTO ref_scan_snmp_oid (oidid, command, prescan, name, oid) VALUES (1, 'walk', 0, 'system', '.1.3.6.1.2.1.1');
INSERT INTO ref_scan_snmp_oid (oidid, command, prescan, name, oid) VALUES (2, 'walk', 1, 'ipNetToMediaPhysAddress', '.1.3.6.1.2.1.4.22.1.2');
INSERT INTO ref_scan_snmp_oid (oidid, command, prescan, name, oid) VALUES (3, 'walk', 0, 'dot1dTpFdbDestPortIfIndex', '.1.3.6.1.2.1.17.4.3.1.2');
INSERT INTO ref_scan_snmp_oid (oidid, command, prescan, name, oid) VALUES (4, 'walk', 0, 'ifIndex', '.1.3.6.1.2.1.2.2.1.1');
INSERT INTO ref_scan_snmp_oid (oidid, command, prescan, name, oid) VALUES (5, 'walk', 0, 'ifDescr', '.1.3.6.1.2.1.2.2.1.2');
INSERT INTO ref_scan_snmp_oid (oidid, command, prescan, name, oid) VALUES (6, 'walk', 0, 'ifAdminStatus', '.1.3.6.1.2.1.2.2.1.7');
INSERT INTO ref_scan_snmp_oid (oidid, command, prescan, name, oid) VALUES (7, 'walk', 0, 'ifOperStatus', '.1.3.6.1.2.1.2.2.1.8');
INSERT INTO ref_scan_snmp_oid (oidid, command, prescan, name, oid) VALUES (8, 'walk', 0, 'ifName', '.1.3.6.1.2.1.31.1.1.1.1');
INSERT INTO ref_scan_snmp_oid (oidid, command, prescan, name, oid) VALUES (9, 'walk', 0, 'ifAlias', '.1.3.6.1.2.1.31.1.1.1.18');
INSERT INTO ref_scan_snmp_oid (oidid, command, prescan, name, oid) VALUES (10, 'walk', 0, 'vtpVlanState', '.1.3.6.1.4.1.9.9.46.1.3.1.1.2');
INSERT INTO ref_scan_snmp_oid (oidid, command, prescan, name, oid) VALUES (11, 'get', 0, 'ipForwarding', '.1.3.6.1.2.1.4.1.0');
INSERT INTO ref_scan_snmp_oid (oidid, command, prescan, name, oid) VALUES (12, 'walk', 0, 'jnxJdhcpLocalServerBindingsMacAddress', '.1.3.6.1.4.1.2636.3.61.61.1.2.1.1.2');
INSERT INTO ref_scan_snmp_oid (oidid, command, prescan, name, oid) VALUES (13, 'walk', 0, 'lldpRemEntry', '.1.0.8802.1.1.2.1.4.1.1');
INSERT INTO ref_scan_snmp_oid (oidid, command, prescan, name, oid) VALUES (14, 'walk', 0, 'cdpCache', '.1.3.6.1.4.1.9.9.23.1.2');
INSERT INTO ref_scan_snmp_oid (oidid, command, prescan, name, oid) VALUES (15, 'walk', 0, 'bsnAPDot3MacAddress', '.1.3.6.1.4.1.14179.2.2.1.1.1');
INSERT INTO ref_scan_snmp_oid (oidid, command, prescan, name, oid) VALUES (16, 'walk', 0, 'bsnApIpAddress', '.1.3.6.1.4.1.14179.2.2.1.1.19');
INSERT INTO ref_scan_snmp_oid (oidid, command, prescan, name, oid) VALUES (17, 'walk', 0, 'bsnAPName', '.1.3.6.1.4.1.14179.2.2.1.1.3');
INSERT INTO ref_scan_snmp_oid (oidid, command, prescan, name, oid) VALUES (18, 'walk', 0, 'ruckusZDWLANAPMacAddr', '.1.3.6.1.4.1.25053.1.2.2.1.1.2.1.1.1');
INSERT INTO ref_scan_snmp_oid (oidid, command, prescan, name, oid) VALUES (19, 'walk', 0, 'ruckusZDWLANAPIPAddr', '.1.3.6.1.4.1.25053.1.2.2.1.1.2.1.1.10');
INSERT INTO ref_scan_snmp_oid (oidid, command, prescan, name, oid) VALUES (20, 'walk', 0, 'ruckusZDWLANAPDescription', '.1.3.6.1.4.1.25053.1.2.2.1.1.2.1.1.2');
INSERT INTO ref_scan_snmp_oid (oidid, command, prescan, name, oid) VALUES (21, 'walk', 0, 'ruckusSCGAPMac', '.1.3.6.1.4.1.25053.1.3.2.1.1.2.2.1.1');
INSERT INTO ref_scan_snmp_oid (oidid, command, prescan, name, oid) VALUES (22, 'walk', 0, 'ruckusSCGAPIp', '.1.3.6.1.4.1.25053.1.3.2.1.1.2.2.1.10');
INSERT INTO ref_scan_snmp_oid (oidid, command, prescan, name, oid) VALUES (23, 'walk', 0, 'ruckusSCGAPName', '.1.3.6.1.4.1.25053.1.3.2.1.1.2.2.1.5');
INSERT INTO ref_scan_snmp_oid (oidid, command, prescan, name, oid) VALUES (24, 'walk', 0, 'ruckusSZAPMac', '.1.3.6.1.4.1.25053.1.4.2.1.1.2.2.1.1');
INSERT INTO ref_scan_snmp_oid (oidid, command, prescan, name, oid) VALUES (25, 'walk', 0, 'ruckusSZAPIp', '.1.3.6.1.4.1.25053.1.4.2.1.1.2.2.1.10');
INSERT INTO ref_scan_snmp_oid (oidid, command, prescan, name, oid) VALUES (26, 'walk', 0, 'ruckusSZAPName', '.1.3.6.1.4.1.25053.1.4.2.1.1.2.2.1.5');
INSERT INTO ref_scan_snmp_oid (oidid, command, prescan, name, oid) VALUES (28, 'get', 0, 'ipCidrRouteNumber', '.1.3.6.1.2.1.4.24.3.0');
INSERT INTO ref_scan_snmp_oid (oidid, command, prescan, name, oid) VALUES (29, 'walk', 0, 'ipAddrTable', '.1.3.6.1.2.1.4.20');
INSERT INTO ref_scan_snmp_oid (oidid, command, prescan, name, oid) VALUES (30, 'walk', 0, 'ipAddressIfIndex', '.1.3.6.1.2.1.4.34.1.3');
INSERT INTO ref_scan_snmp_oid (oidid, command, prescan, name, oid) VALUES (31, 'walk', 0, 'ipAddressType', '.1.3.6.1.2.1.4.34.1.4');
INSERT INTO ref_scan_snmp_oid (oidid, command, prescan, name, oid) VALUES (32, 'walk', 0, 'ipAddressStatus', '.1.3.6.1.2.1.4.34.1.7');
INSERT INTO ref_scan_snmp_oid (oidid, command, prescan, name, oid) VALUES (33, 'walk', FALSE, 'dot1qVlanStatus', '.1.3.6.1.2.1.17.7.1.4.2.1.6');

INSERT INTO ref_static_device (deviceid, ip, active, snmp_community) VALUES (1, '52.9.8.62', 1, NULL);

INSERT INTO ref_wlc_type (wlcid, wlc_type, wlc_name) VALUES (1, 'mist', 'MIST Controller');
INSERT INTO ref_wlc_type (wlcid, wlc_type, wlc_name) VALUES (2, 'cisco_wlc', 'Cisco WLC');
INSERT INTO ref_wlc_type (wlcid, wlc_type, wlc_name) VALUES (3, 'ruckus_zd_wlc', 'Ruckus ZD WLC');
INSERT INTO ref_wlc_type (wlcid, wlc_type, wlc_name) VALUES (4, 'ruckus_scg_wlc', 'Ruckus SCG WLC');
INSERT INTO ref_wlc_type (wlcid, wlc_type, wlc_name) VALUES (5, 'ruckus_sz_wlc', 'Ruckus SZ WLC');
